#ifndef RETROSOC_NETWORK_USER_IP_REGS_H
#define RETROSOC_NETWORK_USER_IP_REGS_H

#include <stdint.h>

#define RS_USER_TIMER_SLOT        UINT8_C(1)
#define RS_USER_TIMER_REG_ID      UINT32_C(0x000)
#define RS_USER_TIMER_REG_DIV     UINT32_C(0x004)
#define RS_USER_TIMER_REG_COUNT   UINT32_C(0x008)

#define RS_USER_GPIO_SLOT         UINT8_C(2)
#define RS_USER_GPIO_REG_ID       UINT32_C(0x000)
#define RS_USER_GPIO_REG_OE       UINT32_C(0x004)
#define RS_USER_GPIO_REG_DATA_OUT UINT32_C(0x008)
#define RS_USER_GPIO_REG_DATA_IN  UINT32_C(0x00C)

#endif
