# Copyright (c) 2023-2026 Yuchi Miao <miaoyuchi@ict.ac.cn>
# retroSoC is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#             http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

# Copy this file to ../local/ics55-production.mk and replace every REQUIRED
# value there. The local copy is ignored by Git.

TOP         := retrosoc_asic
TECHNOLOGY  := ICS55
RTL_ARCHIVE := REQUIRED
BUILD_ROOT  := $(ROOT_PATH)/build

FLOW_PYTHON      := python
TCLSH            := tclsh
LSF_COMMAND      := bsub
LSF_MODE         := batch
LSF_COMMON_ARGS  :=
LSF_SYN_ARGS     := REQUIRED
LSF_FM_ARGS      := REQUIRED
LSF_APR_ARGS     := REQUIRED
LSF_EXTRACT_ARGS := REQUIRED
LSF_STA_ARGS     := REQUIRED
LSF_ECO_ARGS     := REQUIRED
LSF_PV_ARGS      := REQUIRED

DC_SHELL   := dc_shell
FM_SHELL   := fm_shell
INNOVUS    := innovus
STARRC     := StarXtract
PT_SHELL   := pt_shell
CALIBRE    := calibre
CALIBREDRV := calibredrv
V2LVS      := v2lvs

# Synopsys DB views. Every list must be explicit; wildcards are rejected.
STD_DB_MAX  := REQUIRED
STD_DB_WCL  := REQUIRED
STD_DB_TYP  := REQUIRED
STD_DB_MIN  := REQUIRED
STD_DB_ML   := REQUIRED
# DC target subset: H7CR (SVT) and H7CL (LVT) TYP DBs only.
SYN_STD_DB_TYP := REQUIRED
IO_DB_MAX   := REQUIRED
IO_DB_WCL   := REQUIRED
IO_DB_TYP   := REQUIRED
IO_DB_MIN   := REQUIRED
IO_DB_ML    := REQUIRED
SRAM_DB_MAX := REQUIRED
SRAM_DB_WCL := REQUIRED
SRAM_DB_TYP := REQUIRED
SRAM_DB_MIN := REQUIRED
SRAM_DB_ML  := REQUIRED
PLL_DB      := REQUIRED

# Liberty views consumed by Innovus MMMC.
STD_LIB_MAX  := REQUIRED
STD_LIB_WCL  := REQUIRED
STD_LIB_TYP  := REQUIRED
STD_LIB_MIN  := REQUIRED
STD_LIB_ML   := REQUIRED
IO_LIB_MAX   := REQUIRED
IO_LIB_WCL   := REQUIRED
IO_LIB_TYP   := REQUIRED
IO_LIB_MIN   := REQUIRED
IO_LIB_ML    := REQUIRED
SRAM_LIB_MAX := REQUIRED
SRAM_LIB_WCL := REQUIRED
SRAM_LIB_TYP := REQUIRED
SRAM_LIB_MIN := REQUIRED
SRAM_LIB_ML  := REQUIRED
PLL_LIB      := REQUIRED

# Exact internal name from the selected H7CR TYP DB.
SYN_OPERATING_CONDITION_LIBRARY := REQUIRED
SYN_OPERATING_CONDITION         := REQUIRED

# Innovus physical inputs.
TECH_LEF          := REQUIRED
STD_LEFS          := REQUIRED
IO_LEFS           := REQUIRED
MACRO_LEFS        := REQUIRED
CAP_TABLE_CWORST  := REQUIRED
CAP_TABLE_RCWORST := REQUIRED
CAP_TABLE_CBEST   := REQUIRED
CAP_TABLE_RCBEST  := REQUIRED
CAP_TABLE_TYP     := REQUIRED
STREAM_MAP        := REQUIRED

# StarRC technology inputs.
NXTGRD_CWORST  := REQUIRED
NXTGRD_RCWORST := REQUIRED
NXTGRD_CBEST   := REQUIRED
NXTGRD_RCBEST  := REQUIRED
NXTGRD_TYP     := REQUIRED
STARRC_MAP     := REQUIRED

# Calibre and merge inputs.
STD_GDS          := REQUIRED
IO_GDS           := REQUIRED
MACRO_GDS        := REQUIRED
STD_CDL          := REQUIRED
IO_CDL           := REQUIRED
MACRO_CDL        := REQUIRED
CALIBRE_DRC_DECK := REQUIRED
CALIBRE_ANT_DECK := REQUIRED
CALIBRE_LVS_DECK := REQUIRED
STARRC_CORES     := 8

# PDK cell/site/layer names belong in this ignored local configuration.
APR_SITE                 := REQUIRED
APR_CORE_FILLERS         := REQUIRED
APR_IO_FILLERS           := REQUIRED
APR_SIGNAL_PAD_CELLS     := REQUIRED
APR_IO_CORNER_CELL       := REQUIRED
APR_IO_POWER_CELLS       := REQUIRED
APR_IO_OFFSET            := REQUIRED
APR_IO_PITCH             := REQUIRED
APR_ENDCAP_CELLS         := REQUIRED
APR_TIE_HIGH_CELL        := REQUIRED
APR_TIE_LOW_CELL         := REQUIRED
APR_CTS_BUFFER_CELLS     := REQUIRED
APR_CTS_INVERTER_CELLS   := REQUIRED
APR_CLOCK_ROUTING_LAYERS := REQUIRED
APR_SIGNAL_MIN_LAYER     := REQUIRED
APR_SIGNAL_MAX_LAYER     := REQUIRED
APR_POWER_NET            := REQUIRED
APR_GROUND_NET           := REQUIRED
APR_POWER_PINS           := REQUIRED
APR_GROUND_PINS          := REQUIRED
APR_RING_LAYERS          := REQUIRED
APR_STRIPE_LAYER         := REQUIRED
APR_RING_WIDTH           := REQUIRED
APR_RING_SPACING         := REQUIRED
APR_RING_OFFSET          := REQUIRED
APR_STRIPE_WIDTH         := REQUIRED
APR_STRIPE_SPACING       := REQUIRED
APR_STRIPE_PITCH         := REQUIRED
SYN_DONT_USE             := REQUIRED
ECO_SETUP_BUFFERS        := REQUIRED
ECO_HOLD_BUFFERS         := REQUIRED
ECO_SETUP_MARGIN_NS      := 0.0
ECO_HOLD_MARGIN_NS       := 0.0
ECO_MAX_PROCESSES        := 8
ECO_PHYSICAL_MODE        := open_site

# Non-sensitive design intent. Units are micrometres and nanoseconds.
DIE_WIDTH            := 2400
DIE_HEIGHT           := 2400
CORE_MARGIN_LEFT     := 120
CORE_MARGIN_BOTTOM   := 120
CORE_MARGIN_RIGHT    := 120
CORE_MARGIN_TOP      := 120
CORE_UTILIZATION     := 0.60
XTAL_CLK_PERIOD_NS   := 41.666666667
PLL_OUTPUT_PERIOD_NS := 13.888888889
CLOCK_SETUP_UNCERTAINTY_NS := 0.20
CLOCK_HOLD_UNCERTAINTY_NS  := 0.10
CLOCK_TRANSITION_NS        := 0.10
MAX_TRANSITION_NS    := 0.50
MAX_FANOUT           := 32

# Board/device timing is local qualification data. Set YES only when every
# interface budget below is taken from reviewed board and component timing.
IO_TIMING_QUALIFIED := NO

JTAG_INPUT_DELAY_MAX_NS  := REQUIRED
JTAG_INPUT_DELAY_MIN_NS  := REQUIRED
JTAG_INPUT_TRANSITION_NS := REQUIRED
JTAG_OUTPUT_DELAY_MAX_NS := REQUIRED
JTAG_OUTPUT_DELAY_MIN_NS := REQUIRED
JTAG_OUTPUT_LOAD_PF      := REQUIRED

DVP_INPUT_DELAY_MAX_NS  := REQUIRED
DVP_INPUT_DELAY_MIN_NS  := REQUIRED
DVP_INPUT_TRANSITION_NS := REQUIRED

ULPI_INPUT_DELAY_MAX_NS  := REQUIRED
ULPI_INPUT_DELAY_MIN_NS  := REQUIRED
ULPI_INPUT_TRANSITION_NS := REQUIRED
ULPI_OUTPUT_DELAY_MAX_NS := REQUIRED
ULPI_OUTPUT_DELAY_MIN_NS := REQUIRED
ULPI_OUTPUT_LOAD_PF      := REQUIRED

SDRAM_CLOCK_PERIOD_NS    := REQUIRED
SDRAM_INPUT_DELAY_MAX_NS := REQUIRED
SDRAM_INPUT_DELAY_MIN_NS := REQUIRED
SDRAM_INPUT_TRANSITION_NS := REQUIRED
SDRAM_OUTPUT_DELAY_MAX_NS := REQUIRED
SDRAM_OUTPUT_DELAY_MIN_NS := REQUIRED
SDRAM_OUTPUT_LOAD_PF      := REQUIRED

SDIO_CLOCK_PERIOD_NS    := REQUIRED
SDIO_INPUT_DELAY_MAX_NS := REQUIRED
SDIO_INPUT_DELAY_MIN_NS := REQUIRED
SDIO_INPUT_TRANSITION_NS := REQUIRED
SDIO_OUTPUT_DELAY_MAX_NS := REQUIRED
SDIO_OUTPUT_DELAY_MIN_NS := REQUIRED
SDIO_OUTPUT_LOAD_PF      := REQUIRED

XPI_CLOCK_PERIOD_NS    := REQUIRED
XPI_INPUT_DELAY_MAX_NS := REQUIRED
XPI_INPUT_DELAY_MIN_NS := REQUIRED
XPI_INPUT_TRANSITION_NS := REQUIRED
XPI_OUTPUT_DELAY_MAX_NS := REQUIRED
XPI_OUTPUT_DELAY_MIN_NS := REQUIRED
XPI_OUTPUT_LOAD_PF      := REQUIRED

ASYNC_CLOCK_PERIOD_NS    := REQUIRED
ASYNC_INPUT_DELAY_MAX_NS := REQUIRED
ASYNC_INPUT_DELAY_MIN_NS := REQUIRED
ASYNC_INPUT_TRANSITION_NS := REQUIRED
ASYNC_OUTPUT_DELAY_MAX_NS := REQUIRED
ASYNC_OUTPUT_DELAY_MIN_NS := REQUIRED
ASYNC_OUTPUT_LOAD_PF      := REQUIRED

# The qualified ICS55 PLL mode is fixed. Other runtime selections fail to lock.
ICS55_PLL_SUPPORTED_SEL := 0
ICS55_PLL_N             := 2
ICS55_PLL_OD            := 2

# TIMING_IO_MODE_HOOK is required when IO_TIMING_QUALIFIED=YES. It must select
# the reviewed GPIO10-20 DVP mode and cut invalid bidirectional pad feedback.
# Other hooks are optional.
APR_FLOORPLAN_HOOK :=
APR_POWER_HOOK     :=
APR_PLACE_HOOK     :=
APR_CTS_HOOK       :=
APR_ROUTE_HOOK     :=
TIMING_IO_MODE_HOOK := REQUIRED
TIMING_EXCEPTION_HOOK :=

# Required strict thresholds.
MAX_SETUP_VIOLATIONS := 0
MAX_HOLD_VIOLATIONS  := 0
MAX_DRV_VIOLATIONS   := 0
MAX_DRC_RESULTS      := 0
MAX_ANTENNA_RESULTS  := 0