# retroSoC APU block-level timing constraints (top: apb4_apu, IHP130 P8 evidence).
#
# Derived from the SoC core-STA conventions generated by
# physical/smoke/sta/opensta/generate_sdc.py out of
# rtl/mini/integration/clock_reset_domains.json:
#   * same 0.2 ns setup / 0.1 ns hold clock uncertainty
#   * same 0.1 ns clock transition
#   * same reset handling (false path from the asynchronously-asserted reset)
#
# Block-specific assumptions (each documented inline):
#
# 1. Single clock domain. clk_i is the SoC PCLK at 20.833 ns / 48 MHz
#    (clock_reset_domains.json domain "pclk", period_ns 20.833333333).
#    Every apb4_apu port is PCLK-synchronous at the SoC boundary:
#      - the APB4 slave and the AXI4 master attach to PCLK logic; the AXI4
#        master feeds the PCLK side of the u_io_cdc axi4_async_bridge in
#        rtl/mini/top/soc_data_plane.sv, so the PCLK/HP crossing is outside
#        this block;
#      - all four AXI-Stream interfaces (dma_tx/dma_rx/i2s_tx/i2s_rx) are
#        clocked by PCLK in rtl/mini/top/apb4_periph.sv (u_*_axis_if .aclk
#        (clk_i)); the audio-domain crossing lives inside apb4_i2s;
#      - i2s_tx_underrun_i/i2s_rx_overrun_i/i2s_rx_flush_busy_i are
#        PCLK-synchronized event outputs of apb4_i2s (cdc_sync/edge-detect in
#        rtl/ip/serial/apb4_i2s.sv);
#      - owner_i/owner_lock_i/quiesce_i/resource_reset_i/bridge_epoch_i come
#        from the PCLK resource-ownership registers.
# 2. Reset. rst_n_i is the pclk_rst_n_o output of the SoC rst_sync cell
#    (asynchronous assert, synchronous deassert), so the reset port is a
#    false path exactly as in the generated SoC SDC.
# 3. I/O budgeting. The SoC core-STA profile false-paths all top I/O because
#    pad timing is out of scope. For block evidence that would leave every
#    input-to-register and register-to-output path unconstrained, so this
#    SDC instead budgets 30% of the PCLK period (6.25 ns) for the external
#    driver and 30% (6.25 ns) for the external receiver, leaving 40% inside
#    the block. These budgets are a block-level assumption, not measured SoC
#    boundary delays; they exist so that no active APU path is left
#    unconstrained.
# 4. External driving cell and output load match the synthesis ABC
#    constraints (sg13g2_buf_4, 6 fF = 0.006 pF in library units).

set apu_pclk_period 20.833333333
set apu_io_budget 6.25

set clk_pclk_port [get_ports {clk_i}]
if {$clk_pclk_port eq ""} {
  error "required clock port is missing: clk_i"
}
create_clock -name clk_pclk -period $apu_pclk_period $clk_pclk_port
set_clock_uncertainty -setup 0.2 [get_clocks {clk_pclk}]
set_clock_uncertainty -hold 0.1 [get_clocks {clk_pclk}]
set_clock_transition 0.1 [get_clocks {clk_pclk}]

set apu_reset_port [get_ports {rst_n_i}]
if {$apu_reset_port eq ""} {
  error "required reset port is missing: rst_n_i"
}
set_false_path -from $apu_reset_port

set apu_inputs [get_ports -quiet -filter {name != clk_i && name != rst_n_i} [all_inputs]]
set_input_delay -clock clk_pclk $apu_io_budget $apu_inputs
set_output_delay -clock clk_pclk $apu_io_budget [all_outputs]
set_driving_cell -lib_cell sg13g2_buf_4 -pin X $apu_inputs
set_load 0.006 [all_outputs]
