#!/usr/bin/env python3
"""Generate the commercial clock contract from canonical integration data."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
from rtl.mini.pin_map.generate_pin_map import read_map  # noqa: E402
from scripts.check_clock_reset_domains import validate  # noqa: E402
from scripts.setup_helpers import atomic_write  # noqa: E402


EXPECTED_DOMAINS = {
    "external",
    "system",
    "audio",
    "jtag",
    "dvp",
    "usb2_ulpi",
}


def tcl_value(value: object) -> str:
    text = str(value)
    return "{" + text.replace("\\", "\\\\").replace("}", "\\}") + "}"


def load_contract(domains_path: Path, pin_map_path: Path) -> tuple[list[dict[str, Any]], list[str]]:
    validate(domains_path, ROOT)
    document = json.loads(domains_path.read_text(encoding="utf-8"))
    domains = document.get("domains")
    reset_ports = document.get("reset_ports")
    if not isinstance(domains, list) or not isinstance(reset_ports, list):
        raise ValueError("clock/reset inventory has an invalid shape")
    names = {domain.get("name") for domain in domains if isinstance(domain, dict)}
    if names != EXPECTED_DOMAINS:
        raise ValueError(
            "commercial clock domains differ from the canonical set: "
            + ", ".join(sorted(str(name) for name in names))
        )

    pads, _ = read_map(pin_map_path)
    pad_names = {pad.name for pad in pads}
    parsed: list[dict[str, Any]] = []
    for domain in domains:
        sta = domain["sta"]
        source_port = sta.get("source_port", "")
        if source_port and source_port not in pad_names:
            raise ValueError(
                f"clock domain {domain['name']} references an unknown pad: {source_port}"
            )
        object_type = sta.get("object_type", "pin")
        observation = source_port if object_type == "port" else sta["pin"].replace(".", "/")
        parsed.append(
            {
                "name": domain["name"],
                "source_port": source_port,
                "source_domain": sta.get("source_domain", ""),
                "object_type": object_type,
                "observation": observation,
                "period_ns": sta["period_ns"],
                "async_group": sta["async_group"],
            }
        )

    parsed_resets = [str(port) for port in reset_ports]
    unknown_resets = sorted(set(parsed_resets) - pad_names)
    if unknown_resets:
        raise ValueError("reset ports are not declared pads: " + ", ".join(unknown_resets))
    return parsed, parsed_resets


def render(domains: list[dict[str, Any]], reset_ports: list[str]) -> str:
    lines = [
        "# Generated by physical/commercial/scripts/generate_timing_contract.py.",
        "# Source: rtl/mini/integration/clock_reset_domains.json and pin_map.json.",
        "set flow::canonical_clock_domains [dict create \\",
    ]
    for domain in domains:
        fields = []
        for name in (
            "name",
            "source_port",
            "source_domain",
            "object_type",
            "observation",
            "period_ns",
            "async_group",
        ):
            fields.extend((name, tcl_value(domain[name])))
        lines.append(
            "    {0} [dict create {1}] \\".format(
                tcl_value(domain["name"]), " ".join(fields)
            )
        )
    lines.append("]")
    lines.append(
        "set flow::canonical_reset_ports [list {0}]".format(
            " ".join(tcl_value(port) for port in reset_ports)
        )
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--domains", type=Path, required=True)
    parser.add_argument("--pin-map", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        domains, reset_ports = load_contract(args.domains, args.pin_map)
        atomic_write(args.output, render(domains, reset_ports))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
