`timescale 1ns / 1ps

module retrosoc_top (
    input  clk_i,
    inout  rst_n_i,
    inout  uart0_rx_i,
    output uart0_tx_o,
    inout  gpio_io0,
    inout  gpio_io1,
    inout  gpio_io2,
    output psram_sck_o,
    output psram_nss0_o,
    inout  psram_dat0_io,
    inout  psram_dat1_io,
    inout  psram_dat2_io,
    inout  psram_dat3_io,
    output spisd_sck_o,
    output spisd_nss_o,
    output spisd_mosi_o,
    inout  spisd_miso_i,
    output i2s_mclk_o,
    output i2s_sclk_o,
    output i2s_lrck_o,
    output i2s_dacdat_o,
    inout  i2s_adcdat_i,
    output onewire_dat_o,
    inout  i2c_scl_io,
    inout  i2c_sda_io,
    output uart1_tx_o,
    inout  uart1_rx_i,
    output pwm_0_o,
    inout  ps2_clk_i,
    inout  ps2_dat_i,
    output xpi_sck_o,
    output xpi_nss0_o,
    inout  xpi_dat0_io
);

  wire s_sys_clk;
  wire s_aud_clk;
  clk_wiz_0 u_clk_wiz_0 (
      .clk_in1 (clk_i),
      .clk_out1(s_sys_clk),
      .clk_out2(s_aud_clk)
  );

  retrosoc_asic u_retrosoc (
      .extclk_i_pad       (s_sys_clk),
      .audclk_i_pad       (s_aud_clk),
      .ext_rst_n_i_pad    (rst_n_i),
`ifdef HAVE_PLL
      .xi_i_pad           (s_sys_clk),
      .xo_o_pad           (),
      .clk_bypass_i_pad   (1'b1),
      .pll_cfg_0_i_pad    (1'b0),
      .pll_cfg_1_i_pad    (1'b0),
      .pll_cfg_2_i_pad    (1'b0),
`endif
`ifdef CORE_MDD
      .core_sel_0_i_pad   (1'b0),
      .core_sel_1_i_pad   (1'b0),
      .core_sel_2_i_pad   (1'b0),
      .core_sel_3_i_pad   (1'b0),
      .core_sel_4_i_pad   (1'b0),
`endif
`ifdef IP_MDD
      .user_gpio_0_io_pad (),
      .user_gpio_1_io_pad (),
      .user_gpio_2_io_pad (),
      .user_gpio_3_io_pad (),
      .user_gpio_4_io_pad (),
      .user_gpio_5_io_pad (),
      .user_gpio_6_io_pad (),
      .user_gpio_7_io_pad (),
      .user_gpio_8_io_pad (),
      .user_gpio_9_io_pad (),
      .user_gpio_10_io_pad(),
      .user_gpio_11_io_pad(),
      .user_gpio_12_io_pad(),
      .user_gpio_13_io_pad(),
      .user_gpio_14_io_pad(),
      .user_gpio_15_io_pad(),
`endif

      .gpio_0_io_pad     (gpio_io0),
      .gpio_1_io_pad     (gpio_io1),
      .gpio_2_io_pad     (gpio_io2),
      .gpio_3_io_pad     (),
      .gpio_4_io_pad     (),
      .gpio_5_io_pad     (),
      .gpio_6_io_pad     (),
      .gpio_7_io_pad     (),
      .gpio_8_io_pad     (),
      .gpio_9_io_pad     (),
      .gpio_10_io_pad    (),
      .gpio_11_io_pad    (),
      .gpio_12_io_pad    (),
      .gpio_13_io_pad    (),
      .gpio_14_io_pad    (),
      .gpio_15_io_pad    (),
      .gpio_16_io_pad    (),
      .gpio_17_io_pad    (),
      .gpio_18_io_pad    (),
      .gpio_19_io_pad    (),
      .gpio_20_io_pad    (),
      .gpio_21_io_pad    (),
      .gpio_22_io_pad    (),
      .gpio_23_io_pad    (),
      .gpio_24_io_pad    (),
      .gpio_25_io_pad    (),
      .gpio_26_io_pad    (),
      .gpio_27_io_pad    (),
      .gpio_28_io_pad    (),
      .gpio_29_io_pad    (),
      .gpio_30_io_pad    (),
      .gpio_31_io_pad    (),
      .uart0_tx_o_pad    (uart0_tx_o),
      .uart0_rx_i_pad    (uart0_rx_i),
      .xpi_sck_o_pad     (xpi_sck_o),
      .xpi_nss0_o_pad    (xpi_nss0_o),
      .xpi_nss1_o_pad    (),
      .xpi_nss2_o_pad    (),
      .xpi_nss3_o_pad    (),
      .xpi_dat0_io_pad   (xpi_dat0_io),
      .xpi_dat1_io_pad   (),
      .xpi_dat2_io_pad   (),
      .xpi_dat3_io_pad   (),
      .sdram_clk_o_pad   (),
      .sdram_cke_o_pad   (),
      .sdram_cs_n_o_pad  (),
      .sdram_ras_n_o_pad (),
      .sdram_cas_n_o_pad (),
      .sdram_we_n_o_pad  (),
      .sdram_ba0_o_pad   (),
      .sdram_ba1_o_pad   (),
      .sdram_addr0_o_pad (),
      .sdram_addr1_o_pad (),
      .sdram_addr2_o_pad (),
      .sdram_addr3_o_pad (),
      .sdram_addr4_o_pad (),
      .sdram_addr5_o_pad (),
      .sdram_addr6_o_pad (),
      .sdram_addr7_o_pad (),
      .sdram_addr8_o_pad (),
      .sdram_addr9_o_pad (),
      .sdram_addr10_o_pad(),
      .sdram_addr11_o_pad(),
      .sdram_addr12_o_pad(),
      .sdram_dqm0_o_pad  (),
      .sdram_dqm1_o_pad  (),
      .sdram_dq0_io_pad  (),
      .sdram_dq1_io_pad  (),
      .sdram_dq2_io_pad  (),
      .sdram_dq3_io_pad  (),
      .sdram_dq4_io_pad  (),
      .sdram_dq5_io_pad  (),
      .sdram_dq6_io_pad  (),
      .sdram_dq7_io_pad  (),
      .sdram_dq8_io_pad  (),
      .sdram_dq9_io_pad  (),
      .sdram_dq10_io_pad (),
      .sdram_dq11_io_pad (),
      .sdram_dq12_io_pad (),
      .sdram_dq13_io_pad (),
      .sdram_dq14_io_pad (),
      .sdram_dq15_io_pad ()
  );
endmodule
