# timing constr
# create_clock -period 20.000 -waveform {0.000 10.000} [get_ports clk_i]

create_generated_clock -name i2s_mclk_out -source [get_pins u_clk_wiz_0/clk_out2] [get_ports i2s_mclk_o] -divide_by 1

set_clock_groups -name cgp_async -asynchronous -group [get_clocks -include_generated_clocks clk_out1_clk_wiz_0] -group [get_clocks -include_generated_clocks clk_out2_clk_wiz_0]
set_false_path -from [get_ports rst_n_i]

# physical constr
set_property -dict {PACKAGE_PIN L18  IOSTANDARD LVCMOS18} [get_ports clk_i]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS18} [get_ports rst_n_i]
# ps2
set_property -dict {PACKAGE_PIN AB4  IOSTANDARD LVCMOS18} [get_ports ps2_clk_i]
set_property -dict {PACKAGE_PIN AB5  IOSTANDARD LVCMOS18} [get_ports ps2_dat_i]
#onewire
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS18} [get_ports onewire_dat_o]
# i2c1
set_property -dict {PACKAGE_PIN W15  IOSTANDARD LVCMOS18} [get_ports i2c_scl_io]
set_property -dict {PACKAGE_PIN Y15  IOSTANDARD LVCMOS18} [get_ports i2c_sda_io]
# pwm
set_property -dict {PACKAGE_PIN AA9  IOSTANDARD LVCMOS18} [get_ports pwm_2_o]
# spisd
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS18} [get_ports spisd_sck_o]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS18} [get_ports spisd_nss_o]
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS18} [get_ports spisd_mosi_o]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS18} [get_ports spisd_miso_i]
#i2s
set_property -dict {PACKAGE_PIN Y10  IOSTANDARD LVCMOS18} [get_ports i2s_mclk_o]
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD LVCMOS18} [get_ports i2s_sclk_o]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS18} [get_ports i2s_lrck_o]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS18} [get_ports i2s_dacdat_o]
set_property -dict {PACKAGE_PIN W12  IOSTANDARD LVCMOS18} [get_ports i2s_adcdat_i]
# psram mosi(io0) miso(io1) wp(io2) hold(io3)
set_property -dict {PACKAGE_PIN A19  IOSTANDARD LVCMOS18} [get_ports psram_sck_o]
set_property -dict {PACKAGE_PIN A22  IOSTANDARD LVCMOS18} [get_ports psram_nss0_o]
set_property -dict {PACKAGE_PIN C17  IOSTANDARD LVCMOS18} [get_ports psram_dat0_io]
set_property -dict {PACKAGE_PIN A16  IOSTANDARD LVCMOS18} [get_ports psram_dat1_io]
set_property -dict {PACKAGE_PIN D21  IOSTANDARD LVCMOS18} [get_ports psram_dat2_io]
set_property -dict {PACKAGE_PIN B20  IOSTANDARD LVCMOS18} [get_ports psram_dat3_io]
# gpio
set_property -dict {PACKAGE_PIN AA8  IOSTANDARD LVCMOS18} [get_ports gpio_io30]
# uart0
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS18} [get_ports uart0_rx_i]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS18} [get_ports uart0_tx_o]
# xpi
set_property -dict {PACKAGE_PIN A21  IOSTANDARD LVCMOS18} [get_ports xpi_sck_o]
set_property -dict {PACKAGE_PIN C18  IOSTANDARD LVCMOS18} [get_ports xpi_nss0_o]
set_property -dict {PACKAGE_PIN A18  IOSTANDARD LVCMOS18} [get_ports xpi_dat0_io]
set_property -dict {PACKAGE_PIN B21  IOSTANDARD LVCMOS18} [get_ports xpi_dat1_io]
set_property -dict {PACKAGE_PIN B19  IOSTANDARD LVCMOS18} [get_ports xpi_dat2_io]
set_property -dict {PACKAGE_PIN D22  IOSTANDARD LVCMOS18} [get_ports xpi_dat3_io]
# sdram
set_property -dict {PACKAGE_PIN M17  IOSTANDARD LVCMOS18} [get_ports sdram_clk_o]
set_property -dict {PACKAGE_PIN N15  IOSTANDARD LVCMOS18} [get_ports sdram_cke_o]
set_property -dict {PACKAGE_PIN N20  IOSTANDARD LVCMOS18} [get_ports sdram_cs_n_o]
set_property -dict {PACKAGE_PIN N19  IOSTANDARD LVCMOS18} [get_ports sdram_ras_n_o]
set_property -dict {PACKAGE_PIN R20  IOSTANDARD LVCMOS18} [get_ports sdram_cas_n_o]
set_property -dict {PACKAGE_PIN P20  IOSTANDARD LVCMOS18} [get_ports sdram_we_n_o]
set_property -dict {PACKAGE_PIN M20  IOSTANDARD LVCMOS18} [get_ports sdram_ba0_o]
set_property -dict {PACKAGE_PIN K21  IOSTANDARD LVCMOS18} [get_ports sdram_ba1_o]
set_property -dict {PACKAGE_PIN M22  IOSTANDARD LVCMOS18} [get_ports sdram_addr0_o]
set_property -dict {PACKAGE_PIN M21  IOSTANDARD LVCMOS18} [get_ports sdram_addr1_o]
set_property -dict {PACKAGE_PIN J20  IOSTANDARD LVCMOS18} [get_ports sdram_addr2_o]
set_property -dict {PACKAGE_PIN K19  IOSTANDARD LVCMOS18} [get_ports sdram_addr3_o]
set_property -dict {PACKAGE_PIN K18  IOSTANDARD LVCMOS18} [get_ports sdram_addr4_o]
set_property -dict {PACKAGE_PIN J18  IOSTANDARD LVCMOS18} [get_ports sdram_addr5_o]
set_property -dict {PACKAGE_PIN J16  IOSTANDARD LVCMOS18} [get_ports sdram_addr6_o]
set_property -dict {PACKAGE_PIN J17  IOSTANDARD LVCMOS18} [get_ports sdram_addr7_o]
set_property -dict {PACKAGE_PIN K15  IOSTANDARD LVCMOS18} [get_ports sdram_addr8_o]
set_property -dict {PACKAGE_PIN N18  IOSTANDARD LVCMOS18} [get_ports sdram_addr9_o]
set_property -dict {PACKAGE_PIN K20  IOSTANDARD LVCMOS18} [get_ports sdram_addr10_o]
set_property -dict {PACKAGE_PIN K16  IOSTANDARD LVCMOS18} [get_ports sdram_addr11_o]
set_property -dict {PACKAGE_PIN J15  IOSTANDARD LVCMOS18} [get_ports sdram_addr12_o]
set_property -dict {PACKAGE_PIN P21  IOSTANDARD LVCMOS18} [get_ports sdram_dqm0_o]
set_property -dict {PACKAGE_PIN M16  IOSTANDARD LVCMOS18} [get_ports sdram_dqm1_o]
set_property -dict {PACKAGE_PIN W20  IOSTANDARD LVCMOS18} [get_ports sdram_dq0_io]
set_property -dict {PACKAGE_PIN T21  IOSTANDARD LVCMOS18} [get_ports sdram_dq1_io]
set_property -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS18} [get_ports sdram_dq2_io]
set_property -dict {PACKAGE_PIN U22  IOSTANDARD LVCMOS18} [get_ports sdram_dq3_io]
set_property -dict {PACKAGE_PIN W21  IOSTANDARD LVCMOS18} [get_ports sdram_dq4_io]
set_property -dict {PACKAGE_PIN T19  IOSTANDARD LVCMOS18} [get_ports sdram_dq5_io]
set_property -dict {PACKAGE_PIN R19  IOSTANDARD LVCMOS18} [get_ports sdram_dq6_io]
set_property -dict {PACKAGE_PIN R21  IOSTANDARD LVCMOS18} [get_ports sdram_dq7_io]
set_property -dict {PACKAGE_PIN L17  IOSTANDARD LVCMOS18} [get_ports sdram_dq8_io]
set_property -dict {PACKAGE_PIN U15  IOSTANDARD LVCMOS18} [get_ports sdram_dq9_io]
set_property -dict {PACKAGE_PIN V19  IOSTANDARD LVCMOS18} [get_ports sdram_dq10_io]
set_property -dict {PACKAGE_PIN U16  IOSTANDARD LVCMOS18} [get_ports sdram_dq11_io]
set_property -dict {PACKAGE_PIN U14  IOSTANDARD LVCMOS18} [get_ports sdram_dq12_io]
set_property -dict {PACKAGE_PIN V17  IOSTANDARD LVCMOS18} [get_ports sdram_dq13_io]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS18} [get_ports sdram_dq14_io]
set_property -dict {PACKAGE_PIN W17  IOSTANDARD LVCMOS18} [get_ports sdram_dq15_io]
