#ifndef RETROSOC_HAL_NPU_REGS_H
#define RETROSOC_HAL_NPU_REGS_H

#include <stdint.h>

#include <retrosoc/core/soc.h>

#define RS_NPU_REG_IP_ID                         UINT32_C(0x000)
#define RS_NPU_REG_IP_VERSION                    UINT32_C(0x004)
#define RS_NPU_REG_CAPABILITY                    UINT32_C(0x008)
#define RS_NPU_REG_STATUS                        UINT32_C(0x00C)
#define RS_NPU_REG_CONTROL                       UINT32_C(0x010)
#define RS_NPU_REG_IRQ_STATE                     UINT32_C(0x014)
#define RS_NPU_REG_IRQ_ENABLE                    UINT32_C(0x018)
#define RS_NPU_REG_IRQ_TEST                      UINT32_C(0x01C)
#define RS_NPU_REG_JOB_BASE                      UINT32_C(0x020)
#define RS_NPU_REG_JOB_COUNT                     UINT32_C(0x024)
#define RS_NPU_REG_JOB_ID                        UINT32_C(0x028)
#define RS_NPU_REG_TIMEOUT_CYCLES                UINT32_C(0x02C)
#define RS_NPU_REG_RESULT_JOB_ID                 UINT32_C(0x030)
#define RS_NPU_REG_RESULT_CODE                   UINT32_C(0x034)
#define RS_NPU_REG_COMPLETED_DESCRIPTORS         UINT32_C(0x038)
#define RS_NPU_REG_FAULT_DESCRIPTOR              UINT32_C(0x03C)
#define RS_NPU_REG_FAULT_CODE                    UINT32_C(0x040)
#define RS_NPU_REG_FAULT_ADDRESS                 UINT32_C(0x044)
#define RS_NPU_REG_FAULT_INFO                    UINT32_C(0x048)
#define RS_NPU_REG_NUMERIC_PROFILE               UINT32_C(0x04C)
#define RS_NPU_REG_LOCAL_BYTES                   UINT32_C(0x050)
#define RS_NPU_REG_MAC_CONFIG                    UINT32_C(0x054)
#define RS_NPU_REG_MAX_K_SLICE                   UINT32_C(0x058)
#define RS_NPU_REG_MAX_DIMENSION                 UINT32_C(0x05C)
#define RS_NPU_REG_OP_CAPABILITY                 UINT32_C(0x060)
#define RS_NPU_REG_OWNER_STATUS                  UINT32_C(0x064)
#define RS_NPU_REG_RECOVERY_GENERATION           UINT32_C(0x068)
#define RS_NPU_REG_PERF_CONTROL                  UINT32_C(0x06C)
#define RS_NPU_REG_PERF_STATUS                   UINT32_C(0x070)
#define RS_NPU_REG_PERF_JOB_ID                   UINT32_C(0x074)
#define RS_NPU_REG_PERF_GENERATION               UINT32_C(0x078)
#define RS_NPU_REG_DESCRIPTOR_BYTES              UINT32_C(0x07C)
#define RS_NPU_REG_PERF_ACTIVE_CYCLES_LO         UINT32_C(0x080)
#define RS_NPU_REG_PERF_ACTIVE_CYCLES_HI         UINT32_C(0x084)
#define RS_NPU_REG_PERF_CLOCK_PAUSE_CYCLES_LO    UINT32_C(0x088)
#define RS_NPU_REG_PERF_CLOCK_PAUSE_CYCLES_HI    UINT32_C(0x08C)
#define RS_NPU_REG_PERF_USEFUL_MACS_LO           UINT32_C(0x090)
#define RS_NPU_REG_PERF_USEFUL_MACS_HI           UINT32_C(0x094)
#define RS_NPU_REG_PERF_PACK_CYCLES_LO           UINT32_C(0x098)
#define RS_NPU_REG_PERF_PACK_CYCLES_HI           UINT32_C(0x09C)
#define RS_NPU_REG_PERF_LOCAL_BANK_STALL_LO      UINT32_C(0x0A0)
#define RS_NPU_REG_PERF_LOCAL_BANK_STALL_HI      UINT32_C(0x0A4)
#define RS_NPU_REG_PERF_DMA_READ_BYTES_LO        UINT32_C(0x0A8)
#define RS_NPU_REG_PERF_DMA_READ_BYTES_HI        UINT32_C(0x0AC)
#define RS_NPU_REG_PERF_DMA_WRITE_BYTES_LO       UINT32_C(0x0B0)
#define RS_NPU_REG_PERF_DMA_WRITE_BYTES_HI       UINT32_C(0x0B4)
#define RS_NPU_REG_PERF_DMA_STALL_CYCLES_LO      UINT32_C(0x0B8)
#define RS_NPU_REG_PERF_DMA_STALL_CYCLES_HI      UINT32_C(0x0BC)
#define RS_NPU_REG_PERF_REQUANT_STALL_LO         UINT32_C(0x0C0)
#define RS_NPU_REG_PERF_REQUANT_STALL_HI         UINT32_C(0x0C4)
#define RS_NPU_REG_PERF_RETIRED_DESCRIPTORS_LO   UINT32_C(0x0C8)
#define RS_NPU_REG_PERF_RETIRED_DESCRIPTORS_HI   UINT32_C(0x0CC)

#define RS_NPU_IP_ID_VALUE                       UINT32_C(0x4E505531)
#define RS_NPU_IP_VERSION_VALUE                  UINT32_C(0x00010000)
#define RS_NPU_IP_VERSION_MAJOR_MASK             UINT32_C(0xFFFF0000)
#define RS_NPU_IP_VERSION_MAJOR_1                UINT32_C(0x00010000)
#define RS_NPU_CAPABILITY_P2                     UINT32_C(0x00000009)
#define RS_NPU_NUMERIC_PROFILE_VALUE             UINT32_C(0x00000001)
#define RS_NPU_TIMEOUT_CYCLES_RESET              UINT32_C(0x044AA200)
#define RS_NPU_LOCAL_BYTES_VALUE                 UINT32_C(0x00010000)
#define RS_NPU_MAC_CONFIG_VALUE                  UINT32_C(0x00080040)
#define RS_NPU_MAX_K_SLICE                       UINT32_C(1024)
#define RS_NPU_MAX_DIMENSION                     UINT32_C(4096)
#define RS_NPU_MAX_TILE                          UINT32_C(8)
#define RS_NPU_OP_CAPABILITY_MVP                 UINT32_C(0x000001FE)
#define RS_NPU_DESCRIPTOR_ABI_VERSION            UINT32_C(0x0100)
#define RS_NPU_DESCRIPTOR_WORDS                  UINT32_C(32)
#define RS_NPU_DESCRIPTOR_BYTES                  UINT32_C(128)
#define RS_NPU_DESCRIPTOR_BASE_ALIGNMENT         UINT32_C(64)
#define RS_NPU_PARAM_RECORD_BYTES                UINT32_C(16)
#define RS_NPU_ADD_PARAM_BYTES                   UINT32_C(32)
#define RS_NPU_FAULT_DESCRIPTOR_RESET            UINT32_C(0xFFFFFFFF)
#define RS_NPU_IRQ_ALL                           UINT32_C(0x00000007)

#define RS_NPU_CONTROL_START                     UINT32_C(0x00000001)
#define RS_NPU_CONTROL_ABORT                     UINT32_C(0x00000002)
#define RS_NPU_CONTROL_SOFT_RESET                UINT32_C(0x00000004)

#define RS_NPU_STATUS_READY                      UINT32_C(0x00000001)
#define RS_NPU_STATUS_BUSY                       UINT32_C(0x00000002)
#define RS_NPU_STATUS_DRAINING                   UINT32_C(0x00000004)
#define RS_NPU_STATUS_CLOCK_PAUSED               UINT32_C(0x00000008)
#define RS_NPU_STATUS_RECOVERING                 UINT32_C(0x00000010)
#define RS_NPU_STATUS_RESULT_VALID               UINT32_C(0x00000020)

#define RS_NPU_IRQ_DONE                          UINT32_C(0x00000001)
#define RS_NPU_IRQ_ERROR                         UINT32_C(0x00000002)
#define RS_NPU_IRQ_ABORTED                       UINT32_C(0x00000004)

#define RS_NPU_CAPABILITY_PRESENT                UINT32_C(0x00000001)
#define RS_NPU_CAPABILITY_EXECUTION_READY        UINT32_C(0x00000002)
#define RS_NPU_CAPABILITY_PRIVATE_AXI64_DMA      UINT32_C(0x00000004)
#define RS_NPU_CAPABILITY_INTERRUPTS             UINT32_C(0x00000008)
#define RS_NPU_CAPABILITY_DOUBLE_ROUNDING        UINT32_C(0x00000010)
#define RS_NPU_CAPABILITY_NATIVE_HP_CLOCK        UINT32_C(0x00000020)
#define RS_NPU_CAPABILITY_SOFTWARE_ABORT         UINT32_C(0x00000040)

#define RS_NPU_PERF_CONTROL_SNAPSHOT             UINT32_C(0x00000001)
#define RS_NPU_PERF_STATUS_SNAP_BUSY             UINT32_C(0x00000001)
#define RS_NPU_PERF_STATUS_SNAP_VALID            UINT32_C(0x00000002)

#define RS_NPU_OWNER_STATUS_LOCK                 UINT32_C(0x00000100)
#define RS_NPU_OWNER_STATUS_QUIESCE              UINT32_C(0x00000200)
#define RS_NPU_OWNER_STATUS_RESET_REQUEST        UINT32_C(0x00000400)

#define RS_NPU_MAC_CONFIG_DENSE_SHIFT            0U
#define RS_NPU_MAC_CONFIG_DENSE_MASK             UINT32_C(0x0000FFFF)
#define RS_NPU_MAC_CONFIG_DEPTHWISE_SHIFT        16U
#define RS_NPU_MAC_CONFIG_DEPTHWISE_MASK         UINT32_C(0xFFFF0000)
#define RS_NPU_JOB_COUNT_VALUE_SHIFT             0U
#define RS_NPU_JOB_COUNT_VALUE_MASK              UINT32_C(0x0000FFFF)
#define RS_NPU_OWNER_STATUS_OWNER_SHIFT          0U
#define RS_NPU_OWNER_STATUS_OWNER_MASK           UINT32_C(0x00000003)
#define RS_NPU_FAULT_INFO_AXI_RESPONSE_SHIFT     0U
#define RS_NPU_FAULT_INFO_AXI_RESPONSE_MASK      UINT32_C(0x00000003)
#define RS_NPU_FAULT_INFO_DIRECTION_SHIFT        2U
#define RS_NPU_FAULT_INFO_DIRECTION_MASK         UINT32_C(0x0000000C)
#define RS_NPU_FAULT_INFO_LANE_SHIFT             8U
#define RS_NPU_FAULT_INFO_LANE_MASK              UINT32_C(0x0000FF00)
#define RS_NPU_VERSION_OPCODE_VERSION_SHIFT      16U
#define RS_NPU_VERSION_OPCODE_VERSION_MASK       UINT32_C(0xFFFF0000)
#define RS_NPU_VERSION_OPCODE_OPCODE_SHIFT       0U
#define RS_NPU_VERSION_OPCODE_OPCODE_MASK        UINT32_C(0x000000FF)

#define RS_NPU_FAULT_INFO_DIRECTION_INTERNAL     0U
#define RS_NPU_FAULT_INFO_DIRECTION_READ         1U
#define RS_NPU_FAULT_INFO_DIRECTION_WRITE        2U
#define RS_NPU_FAULT_INFO_LANE_NONE              UINT32_C(0xFF)

#define RS_NPU_RESULT_NONE                       0U
#define RS_NPU_RESULT_DONE                       1U
#define RS_NPU_RESULT_ERROR                      2U
#define RS_NPU_RESULT_ABORTED                    3U
#define RS_NPU_RESULT_RESET_CANCELLED            4U

#define RS_NPU_FAULT_NONE                        0U
#define RS_NPU_FAULT_DESCRIPTOR                  1U
#define RS_NPU_FAULT_UNSUPPORTED                 2U
#define RS_NPU_FAULT_RANGE                       3U
#define RS_NPU_FAULT_AXI_READ                    4U
#define RS_NPU_FAULT_AXI_WRITE                   5U
#define RS_NPU_FAULT_AXI_PROTOCOL                6U
#define RS_NPU_FAULT_ARITHMETIC                  7U
#define RS_NPU_FAULT_NO_PROGRESS                 8U
#define RS_NPU_FAULT_LOCAL_STATE                 9U
#define RS_NPU_FAULT_RESET_CANCELLED             10U

#define RS_NPU_OPCODE_CONV2D                     1U
#define RS_NPU_OPCODE_DEPTHWISE3X3               2U
#define RS_NPU_OPCODE_FULLY_CONNECTED            3U
#define RS_NPU_OPCODE_ADD                        4U
#define RS_NPU_OPCODE_MAX_POOL                   5U
#define RS_NPU_OPCODE_AVERAGE_POOL               6U
#define RS_NPU_OPCODE_GLOBAL_AVERAGE_POOL        7U
#define RS_NPU_OPCODE_CLAMP                      8U

#define RS_NPU_DESCRIPTOR_WORD_VERSION_OPCODE    0U
#define RS_NPU_DESCRIPTOR_WORD_RESERVED          1U
#define RS_NPU_DESCRIPTOR_WORD_INPUT0_BASE       2U
#define RS_NPU_DESCRIPTOR_WORD_INPUT1_BASE       3U
#define RS_NPU_DESCRIPTOR_WORD_OUTPUT_BASE       4U
#define RS_NPU_DESCRIPTOR_WORD_PARAM_BASE        5U
#define RS_NPU_DESCRIPTOR_WORD_INPUT_HW          6U
#define RS_NPU_DESCRIPTOR_WORD_CHANNELS          7U
#define RS_NPU_DESCRIPTOR_WORD_OUTPUT_HW         8U
#define RS_NPU_DESCRIPTOR_WORD_INPUT0_ROW_BYTES  9U
#define RS_NPU_DESCRIPTOR_WORD_OUTPUT_ROW_BYTES  10U
#define RS_NPU_DESCRIPTOR_WORD_INPUT1_ROW_BYTES  11U
#define RS_NPU_DESCRIPTOR_WORD_KERNEL_STRIDE     12U
#define RS_NPU_DESCRIPTOR_WORD_PADDING           13U
#define RS_NPU_DESCRIPTOR_WORD_TILE_HW           14U
#define RS_NPU_DESCRIPTOR_WORD_K_SLICE           15U
#define RS_NPU_DESCRIPTOR_WORD_INPUT0_BYTES      16U
#define RS_NPU_DESCRIPTOR_WORD_INPUT1_BYTES      17U
#define RS_NPU_DESCRIPTOR_WORD_OUTPUT_BYTES      18U
#define RS_NPU_DESCRIPTOR_WORD_PARAM_BYTES       19U
#define RS_NPU_DESCRIPTOR_WORD_INPUT0_ZERO       20U
#define RS_NPU_DESCRIPTOR_WORD_INPUT1_ZERO       21U
#define RS_NPU_DESCRIPTOR_WORD_OUTPUT_ZERO       22U
#define RS_NPU_DESCRIPTOR_WORD_ACTIVATION_BOUNDS 23U
#define RS_NPU_DESCRIPTOR_WORD_WEIGHT_BASE       24U
#define RS_NPU_DESCRIPTOR_WORD_WEIGHT_BYTES      25U

#if defined(RS_SOC_APB4_NPU_BASE)
#define RS_NPU_REG(offset) RS_SOC_REG32(RS_SOC_APB4_NPU_BASE, (offset))
#endif

#endif
