#ifndef RETROSOC_HAL_ONCHIP_SRAM_REGS_H
#define RETROSOC_HAL_ONCHIP_SRAM_REGS_H

#include <stdint.h>

#include <retrosoc/generated/memory_map.h>

/* Keep this handwritten ABI synchronized with onchip_ram_define.svh. */
#define RS_ONCHIP_SRAM_REG_IP_ID                UINT32_C(0x000)
#define RS_ONCHIP_SRAM_REG_IP_VERSION           UINT32_C(0x004)
#define RS_ONCHIP_SRAM_REG_CAPABILITY           UINT32_C(0x008)
#define RS_ONCHIP_SRAM_REG_MEMORY_BYTES         UINT32_C(0x00C)
#define RS_ONCHIP_SRAM_REG_BANK_COUNT           UINT32_C(0x010)
#define RS_ONCHIP_SRAM_REG_BANK_BYTES           UINT32_C(0x014)
#define RS_ONCHIP_SRAM_REG_PERF_READ_REQUESTS   UINT32_C(0x020)
#define RS_ONCHIP_SRAM_REG_PERF_WRITE_REQUESTS  UINT32_C(0x024)
#define RS_ONCHIP_SRAM_REG_PERF_READ_BEATS      UINT32_C(0x028)
#define RS_ONCHIP_SRAM_REG_PERF_WRITE_BEATS     UINT32_C(0x02C)
#define RS_ONCHIP_SRAM_REG_PERF_STALL_CYCLES    UINT32_C(0x030)
#define RS_ONCHIP_SRAM_REG_PERF_ERROR_RESPONSES UINT32_C(0x034)

#define RS_ONCHIP_SRAM_IP_ID_VALUE              UINT32_C(0x5352414D)
#define RS_ONCHIP_SRAM_IP_VERSION_VALUE         UINT32_C(0x00010000)
#define RS_ONCHIP_SRAM_BANK_BYTES_VALUE         UINT32_C(4096)

#define RS_ONCHIP_SRAM_CAP_PRESENT              UINT32_C(0x00000001)
#define RS_ONCHIP_SRAM_CAP_NATIVE_AXI4          UINT32_C(0x00000002)
#define RS_ONCHIP_SRAM_CAP_BYTE_WRITE           UINT32_C(0x00000004)
#define RS_ONCHIP_SRAM_CAP_FIXED                UINT32_C(0x00000008)
#define RS_ONCHIP_SRAM_CAP_INCR                 UINT32_C(0x00000010)
#define RS_ONCHIP_SRAM_CAP_WRAP                 UINT32_C(0x00000020)
#define RS_ONCHIP_SRAM_CAP_PERFORMANCE          UINT32_C(0x00000040)
#define RS_ONCHIP_SRAM_CAP_MAX_BEATS_SHIFT      UINT32_C(8)
#define RS_ONCHIP_SRAM_CAP_MAX_BEATS_MASK       UINT32_C(0x0000FF00)
#define RS_ONCHIP_SRAM_CAP_DATA_BYTES_SHIFT     UINT32_C(16)
#define RS_ONCHIP_SRAM_CAP_DATA_BYTES_MASK      UINT32_C(0x00FF0000)

#define RS_ONCHIP_SRAM_REG(offset)                                                                 \
    (*(volatile uint32_t *)(uintptr_t)(RS_SOC_APB4_SRAM_BASE + (offset)))

#endif
