{ 
    +lint=all; 
    -file=../../ip/3rd_party/spfs_model/N25Qxxx.v,../../../pdk/IHP-Open-PDK/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v,../../clusterip/i2c/model/at24cxxx.sv,../../clusterip/spi/model/w25q128jvxim.sv,../core/picorv32_ver.v,../core/picorv32.v,../../clusterip/common/rtl/cdc/cdc_2phase.sv,../../clusterip/common/rtl/utils/register.sv,../../clusterip/uart/model/rs232.sv,../tb/retrosoc_tb.sv,../../clusterip/i2s/model/mic.sv,../../ip/native/ESP_PSRAM64H.sv,../../ip/3rd_party/spfs_model/include/Decoders.h,../../ip/3rd_party/spfs_model/include/PLRSDetectors.h;
}