`timescale 1ns / 1ps

// NPU-P3 npu_job_decoder unit test: the decoder drives a production npu_dma
// read channel against a byte-memory BFM with optional per-beat SLVERR/DECERR
// and malformed-RID injection. Descriptor images and expected verdicts come
// from plusargs generated by tests/test_npu_rtl_p3.py with
// scripts/npu_descriptors.py as the golden validator. Covered: valid records
// of every opcode (emitted record fields compared word-for-word against the
// image), every validator rejection class with first-fault code/word/index,
// multi-descriptor in-order traversal, fetch SLVERR/DECERR and protocol
// faults with forwarded address/response, descriptor-region truncation,
// pause retention mid-fetch, and no reuse of the launch slot after a terminal
// fault without a fresh job_start.
`include "npu_define.svh"

module npu_job_decoder_tb;
  localparam logic [31:0] SramBase = 32'h3000_0000;
  localparam int unsigned MemoryBytes = 262144;
  localparam int unsigned PhaseTimeout = 20000;

  // plusarg-driven case configuration
  string        s_img_path;
  logic  [31:0] s_job_base;
  logic  [31:0] s_job_count;
  logic  [31:0] s_mode;  // 0 accept, 1 validation fault, 2 fetch fault, 3 pause fetch
  logic  [31:0] s_exp_fcode;
  logic  [31:0] s_exp_findex;
  logic         s_exp_wordless;
  logic  [31:0] s_exp_fword;
  logic  [31:0] s_rderr_addr;
  logic  [31:0] s_rderr_code;
  logic  [31:0] s_rderr_badid;

  logic         clk_hp_i = 1'b0;
  logic         rst_hp_n_i = 1'b0;
  logic         clear_i = 1'b0;
  logic         block_new_i = 1'b0;
  logic         dec_pause_ok;
  logic         job_start_i = 1'b0;
  logic  [31:0] job_base_i = '0;
  logic  [15:0] job_count_i = '0;
  logic         s_dec_read_req_valid;
  logic         s_dec_read_req_ready;
  logic  [31:0] s_dec_read_addr;
  logic  [31:0] s_dec_read_bytes;
  logic         s_dec_read_data_valid;
  logic         s_dec_read_data_ready;
  logic  [63:0] s_dec_read_data;
  logic  [ 7:0] s_dec_read_keep;
  logic         s_dec_read_last;
  logic         rec_valid_o;
  logic         rec_ready_i = 1'b0;
  logic  [ 3:0] rec_opcode_o;
  logic [12:0] rec_h_o, rec_w_o, rec_cin_o, rec_cout_o, rec_oh_o, rec_ow_o;
  logic [31:0] rec_input0_base_o, rec_output_base_o, rec_weight_base_o, rec_param_base_o;
  logic [31:0] rec_input0_row_bytes_o, rec_output_row_bytes_o;
  logic [7:0] rec_kh_o, rec_kw_o, rec_sh_o, rec_sw_o;
  logic [7:0] rec_pad_top_o, rec_pad_left_o, rec_input0_zero_o;
  logic [31:0] rec_weight_bytes_o, rec_param_bytes_o;
  logic        [15:0] rec_desc_index_o;
  logic               retired_i = 1'b0;
  logic               all_done_o;
  logic               busy_o;
  logic        [15:0] cur_desc_index_o;
  logic               progress_o;
  logic               fault_req_o;
  logic        [ 3:0] fault_code_o;
  logic        [31:0] fault_addr_o;
  logic        [31:0] fault_info_o;
  logic        [31:0] fault_desc_o;

  logic        [ 7:0] s_memory           [0:MemoryBytes-1];
  // read channel BFM state
  logic               s_rvalid_q;
  logic        [ 2:0] s_rid_q;
  logic        [ 1:0] s_rresp_q;
  logic        [31:0] s_raddr_q;
  logic        [63:0] s_rdata_q;
  logic        [ 2:0] s_rsize_q;
  logic        [ 8:0] s_rbeats_q;
  // counters and bookkeeping
  int unsigned        s_ar_count;
  int unsigned        s_rd_outstanding_q;
  int unsigned        s_rec_count;
  logic               s_saw_all_done_q;
  string              s_phase;
  int unsigned        s_phase_cycles_q;
  logic               s_progress;
  logic               s_pause_armed_i;
  logic               s_pause_done_q;

  axi4_if #(
      .ADDR_WIDTH(32),
      .DATA_WIDTH(64),
      .ID_WIDTH  (3),
      .USER_WIDTH(1)
  ) npu_axi4 (
      .aclk   (clk_hp_i),
      .aresetn(rst_hp_n_i)
  );

  npu_dma u_dma (
      .clk_hp_i          (clk_hp_i),
      .rst_hp_n_i        (rst_hp_n_i),
      .clear_i           (clear_i),
      .block_new_i       (block_new_i),
      .pause_ack_o       (),
      .read_req_valid_i  (s_dec_read_req_valid),
      .read_req_ready_o  (s_dec_read_req_ready),
      .read_addr_i       (s_dec_read_addr),
      .read_bytes_i      (s_dec_read_bytes),
      .read_data_valid_o (s_dec_read_data_valid),
      .read_data_ready_i (s_dec_read_data_ready),
      .read_data_o       (s_dec_read_data),
      .read_keep_o       (s_dec_read_keep),
      .read_last_o       (s_dec_read_last),
      .write_req_valid_i (1'b0),
      .write_req_ready_o (),
      .write_addr_i      (32'd0),
      .write_bytes_i     (32'd0),
      .write_data_valid_i(1'b0),
      .write_data_ready_o(),
      .write_data_i      (64'd0),
      .write_keep_i      (8'd0),
      .write_last_i      (1'b0),
      .write_done_o      (),
      .busy_o            (),
      .read_busy_o       (s_dma_read_busy),
      .write_busy_o      (),
      .read_bytes_o      (),
      .write_bytes_o     (),
      .stall_cycles_o    (),
      .fault_o           (s_dma_fault),
      .fault_code_o      (s_dma_fault_code),
      .fault_addr_o      (s_dma_fault_addr),
      .fault_resp_o      (s_dma_fault_resp),
      .read_cmd_err_o    (),
      .write_cmd_err_o   (),
      .axi4              (npu_axi4)
  );
  logic        s_dma_read_busy;
  logic        s_dma_fault;
  logic [ 3:0] s_dma_fault_code;
  logic [31:0] s_dma_fault_addr;
  logic [ 1:0] s_dma_fault_resp;

  npu_job_decoder u_dut (
      .clk_hp_i              (clk_hp_i),
      .rst_hp_n_i            (rst_hp_n_i),
      .clear_i               (clear_i),
      .block_new_i           (block_new_i),
      .pause_ok_o            (dec_pause_ok),
      .job_start_i           (job_start_i),
      .job_base_i            (job_base_i),
      .job_count_i           (job_count_i),
      .read_req_valid_o      (s_dec_read_req_valid),
      .read_req_ready_i      (s_dec_read_req_ready),
      .read_addr_o           (s_dec_read_addr),
      .read_bytes_o          (s_dec_read_bytes),
      .read_data_valid_i     (s_dec_read_data_valid),
      .read_data_ready_o     (s_dec_read_data_ready),
      .read_data_i           (s_dec_read_data),
      .read_last_i           (s_dec_read_last),
      .dma_read_busy_i       (s_dma_read_busy),
      .dma_fault_i           (s_dma_fault),
      .dma_fault_code_i      (s_dma_fault_code),
      .dma_fault_addr_i      (s_dma_fault_addr),
      .dma_fault_resp_i      (s_dma_fault_resp),
      .rec_valid_o           (rec_valid_o),
      .rec_ready_i           (rec_ready_i),
      .rec_opcode_o          (rec_opcode_o),
      .rec_h_o               (rec_h_o),
      .rec_w_o               (rec_w_o),
      .rec_cin_o             (rec_cin_o),
      .rec_cout_o            (rec_cout_o),
      .rec_oh_o              (rec_oh_o),
      .rec_ow_o              (rec_ow_o),
      .rec_input0_base_o     (rec_input0_base_o),
      .rec_output_base_o     (rec_output_base_o),
      .rec_weight_base_o     (rec_weight_base_o),
      .rec_param_base_o      (rec_param_base_o),
      .rec_input0_row_bytes_o(rec_input0_row_bytes_o),
      .rec_output_row_bytes_o(rec_output_row_bytes_o),
      .rec_kh_o              (rec_kh_o),
      .rec_kw_o              (rec_kw_o),
      .rec_sh_o              (rec_sh_o),
      .rec_sw_o              (rec_sw_o),
      .rec_pad_top_o         (rec_pad_top_o),
      .rec_pad_left_o        (rec_pad_left_o),
      .rec_input0_zero_o     (rec_input0_zero_o),
      .rec_weight_bytes_o    (rec_weight_bytes_o),
      .rec_param_bytes_o     (rec_param_bytes_o),
      .rec_desc_index_o      (rec_desc_index_o),
      .retired_i             (retired_i),
      .all_done_o            (all_done_o),
      .busy_o                (busy_o),
      .cur_desc_index_o      (cur_desc_index_o),
      .progress_o            (progress_o),
      .fault_req_o           (fault_req_o),
      .fault_code_o          (fault_code_o),
      .fault_addr_o          (fault_addr_o),
      .fault_info_o          (fault_info_o),
      .fault_desc_o          (fault_desc_o)
  );

  always #5 clk_hp_i = ~clk_hp_i;

  function automatic logic [7:0] memory_byte(input logic [31:0] address_i);
    if ((address_i >= SramBase) && (address_i < (SramBase + MemoryBytes))) begin
      return s_memory[address_i-SramBase];
    end
    return 8'd0;
  endfunction

  function automatic logic [63:0] memory_word(input logic [31:0] address_i);
    logic [63:0] data;
    logic [31:0] aligned_address;
    begin
      data            = '0;
      aligned_address = {address_i[31:3], 3'b000};
      for (int unsigned lane = 0; lane < 8; lane++) begin
        data[lane*8+:8] = memory_byte(aligned_address + lane);
      end
      return data;
    end
  endfunction

  function automatic logic [31:0] image_word(input int unsigned desc_i, input int unsigned word_i);
    logic [31:0] value;
    begin
      value = '0;
      for (int unsigned lane = 0; lane < 4; lane++) begin
        value[lane*8+:8] =
            memory_byte(s_job_base + 32'(desc_i) * 32'd128 + 32'(word_i) * 32'd4 + 32'(lane));
      end
      return value;
    end
  endfunction

  function automatic logic [1:0] bfm_read_resp(input logic [31:0] beat_addr_i);
    if ((s_rderr_addr != 32'hffff_ffff) && (beat_addr_i == s_rderr_addr)) begin
      return s_rderr_code[1:0];
    end
    return 2'b00;
  endfunction

  // ------------------------- AXI read slave BFM -------------------------
  assign npu_axi4.arready = !s_hold_ar_i && !s_rvalid_q;
  assign npu_axi4.rid     = s_rid_q;
  assign npu_axi4.rdata   = s_rdata_q;
  assign npu_axi4.rresp   = s_rresp_q;
  assign npu_axi4.rlast   = (s_rbeats_q == 9'd1);
  assign npu_axi4.ruser   = '0;
  assign npu_axi4.rvalid  = !s_hold_r_i && s_rvalid_q;
  // the decoder never writes
  assign npu_axi4.awready = 1'b0;
  assign npu_axi4.wready  = 1'b0;
  assign npu_axi4.bid     = '0;
  assign npu_axi4.bresp   = 2'b00;
  assign npu_axi4.buser   = '0;
  assign npu_axi4.bvalid  = 1'b0;

  logic s_hold_ar_i;
  logic s_hold_r_i;

  always_ff @(posedge clk_hp_i or negedge rst_hp_n_i) begin
    if (!rst_hp_n_i) begin
      s_rvalid_q         <= 1'b0;
      s_rid_q            <= '0;
      s_rresp_q          <= 2'd0;
      s_raddr_q          <= '0;
      s_rdata_q          <= '0;
      s_rsize_q          <= '0;
      s_rbeats_q         <= '0;
      s_ar_count         <= 0;
      s_rd_outstanding_q <= 0;
    end else if (clear_i) begin
      s_rvalid_q         <= 1'b0;
      s_rbeats_q         <= '0;
      s_rd_outstanding_q <= 0;
    end else begin
      if (npu_axi4.arvalid && npu_axi4.arready) begin
        if (s_rd_outstanding_q != 0) begin
          $fatal(1, "NPU decoder TB: second outstanding read");
        end
        if ((npu_axi4.araddr & ((32'd1 << npu_axi4.arsize) - 32'd1)) != 32'd0) begin
          $fatal(1, "NPU decoder TB: unaligned read transfer");
        end
        if ((npu_axi4.arsize != 3'd3) && (npu_axi4.arlen != 8'd0)) begin
          $fatal(1, "NPU decoder TB: multi-beat narrow read burst");
        end
        if ({1'b0, npu_axi4.araddr[11:0]} + (({5'd0, npu_axi4.arlen} + 13'd1) << npu_axi4.arsize)
            > 13'd4096) begin
          $fatal(1, "NPU decoder TB: read burst crossed a 4 KiB boundary");
        end
        if ((npu_axi4.araddr < s_job_base) ||
            (npu_axi4.araddr >= (s_job_base + {16'd0, s_job_count[15:0], 7'd0}))) begin
          $fatal(1, "NPU decoder TB: read escaped the descriptor region");
        end
        s_rvalid_q <= 1'b1;
        s_rid_q            <= ((s_rderr_badid != 32'd0) &&
                               (npu_axi4.araddr == {s_rderr_addr[31:3], 3'b000})) ? 3'd1 : 3'd0;
        s_rresp_q <= bfm_read_resp(npu_axi4.araddr);
        s_raddr_q <= npu_axi4.araddr;
        s_rdata_q <= memory_word(npu_axi4.araddr);
        s_rsize_q <= npu_axi4.arsize;
        s_rbeats_q <= {1'b0, npu_axi4.arlen} + 1'b1;
        s_ar_count <= s_ar_count + 1;
        s_rd_outstanding_q <= s_rd_outstanding_q + 1;
      end else if (s_rvalid_q && npu_axi4.rvalid && npu_axi4.rready) begin
        if (s_rbeats_q == 9'd1) begin
          s_rvalid_q         <= 1'b0;
          s_rbeats_q         <= '0;
          s_rd_outstanding_q <= s_rd_outstanding_q - 1;
        end else begin
          s_raddr_q  <= s_raddr_q + (32'd1 << s_rsize_q);
          s_rdata_q  <= memory_word(s_raddr_q + (32'd1 << s_rsize_q));
          s_rresp_q  <= bfm_read_resp(s_raddr_q + (32'd1 << s_rsize_q));
          s_rbeats_q <= s_rbeats_q - 1'b1;
        end
      end
      if (npu_axi4.awvalid || npu_axi4.wvalid) begin
        $fatal(1, "NPU decoder TB: unexpected write channel activity");
      end
    end
  end

  // sticky all_done capture (the pulse is one cycle)
  always_ff @(posedge clk_hp_i or negedge rst_hp_n_i) begin
    if (!rst_hp_n_i) begin
      s_saw_all_done_q <= 1'b0;
    end else if (all_done_o) begin
      s_saw_all_done_q <= 1'b1;
    end
  end

  // progress watchdog: any decoder or bus forward motion resets the phase timer
  assign s_progress = (npu_axi4.arvalid && npu_axi4.arready) ||
                      (npu_axi4.rvalid && npu_axi4.rready) ||
                      (s_dec_read_req_valid && s_dec_read_req_ready) ||
                      (rec_valid_o && rec_ready_i) || retired_i || progress_o;

  always_ff @(posedge clk_hp_i or negedge rst_hp_n_i) begin
    if (!rst_hp_n_i) begin
      s_phase_cycles_q <= 0;
    end else begin
      if (s_progress) begin
        s_phase_cycles_q <= 0;
      end else begin
        s_phase_cycles_q <= s_phase_cycles_q + 1;
        if (s_phase_cycles_q >= PhaseTimeout) begin
          $fatal(1, "NPU decoder TB phase timed out: %s", s_phase);
        end
      end
    end
  end

  // pause stimulus: hold block_new_i for a 30-cycle window once the fetch
  // command of descriptor 0 is presented
  logic [5:0] s_pause_cnt_q;
  always_ff @(posedge clk_hp_i or negedge rst_hp_n_i) begin
    if (!rst_hp_n_i) begin
      block_new_i    <= 1'b0;
      s_pause_done_q <= 1'b0;
      s_pause_cnt_q  <= 6'd0;
    end else begin
      if (s_pause_armed_i && !s_pause_done_q && s_dec_read_req_valid) begin
        block_new_i    <= 1'b1;
        s_pause_cnt_q  <= 6'd0;
        s_pause_done_q <= 1'b1;
      end else if (s_pause_done_q && block_new_i) begin
        if (s_pause_cnt_q == 6'd30) begin
          block_new_i <= 1'b0;
        end else begin
          s_pause_cnt_q <= s_pause_cnt_q + 6'd1;
        end
      end
    end
  end

  task automatic idle_cycles(input int unsigned cycles_i);
    begin
      repeat (cycles_i) @(posedge clk_hp_i);
    end
  endtask

  task automatic set_phase(input string name_i);
    begin
      @(negedge clk_hp_i);
      s_phase = name_i;
      idle_cycles(1);
    end
  endtask

  task automatic load_image(input string path_i, input logic [31:0] base_i);
    logic        [31:0] s_img       [0:65535];
    int unsigned        s_img_words;
    begin
      $readmemh(path_i, s_img);
      s_img_words = 32'(s_job_count) * 32;
      for (int unsigned index = 0; index < s_img_words; index++) begin
        for (int unsigned lane = 0; lane < 4; lane++) begin
          s_memory[base_i-SramBase+index*4+lane] = s_img[index][lane*8+:8];
        end
      end
    end
  endtask

  task automatic launch_job;
    begin
      @(negedge clk_hp_i);
      job_base_i  = s_job_base;
      job_count_i = s_job_count[15:0];
      job_start_i = 1'b1;
      @(negedge clk_hp_i);
      job_start_i = 1'b0;
    end
  endtask

  task automatic check_record(input int unsigned desc_i);
    logic [31:0] s_w0, s_w6, s_w7, s_w8, s_w12, s_w13, s_w20;
    begin
      s_w0  = image_word(desc_i, 0);
      s_w6  = image_word(desc_i, 6);
      s_w7  = image_word(desc_i, 7);
      s_w8  = image_word(desc_i, 8);
      s_w12 = image_word(desc_i, 12);
      s_w13 = image_word(desc_i, 13);
      s_w20 = image_word(desc_i, 20);
      if (32'(rec_opcode_o) != {24'd0, s_w0[7:0]}) begin
        $fatal(1, "record %0d opcode mismatch: %h", desc_i, rec_opcode_o);
      end
      if ((20'(rec_h_o) != {4'd0, s_w6[15:0]}) || (20'(rec_w_o) != {4'd0, s_w6[31:16]})) begin
        $fatal(1, "record %0d input geometry mismatch", desc_i);
      end
      if ((20'(rec_cin_o) != {4'd0, s_w7[15:0]}) || (20'(rec_cout_o) != {4'd0, s_w7[31:16]})) begin
        $fatal(1, "record %0d channels mismatch", desc_i);
      end
      if ((20'(rec_oh_o) != {4'd0, s_w8[15:0]}) || (20'(rec_ow_o) != {4'd0, s_w8[31:16]})) begin
        $fatal(1, "record %0d output geometry mismatch", desc_i);
      end
      if ((rec_input0_base_o != image_word(
              desc_i, 2
          )) || (rec_output_base_o != image_word(
              desc_i, 4
          )) || (rec_weight_base_o != image_word(
              desc_i, 24
          )) || (rec_param_base_o != image_word(
              desc_i, 5
          ))) begin
        $fatal(1, "record %0d base address mismatch", desc_i);
      end
      if ((rec_input0_row_bytes_o != image_word(
              desc_i, 9
          )) || (rec_output_row_bytes_o != image_word(
              desc_i, 10
          ))) begin
        $fatal(1, "record %0d row stride mismatch", desc_i);
      end
      if ((rec_kh_o != s_w12[7:0]) || (rec_kw_o != s_w12[15:8]) ||
          (rec_sh_o != s_w12[23:16]) || (rec_sw_o != s_w12[31:24])) begin
        $fatal(1, "record %0d kernel/stride mismatch", desc_i);
      end
      if ((rec_pad_top_o != s_w13[7:0]) || (rec_pad_left_o != s_w13[23:16]) ||
          (rec_input0_zero_o != s_w20[7:0])) begin
        $fatal(1, "record %0d padding/zero mismatch", desc_i);
      end
      if ((rec_weight_bytes_o != image_word(
              desc_i, 25
          )) || (rec_param_bytes_o != image_word(
              desc_i, 19
          ))) begin
        $fatal(1, "record %0d weight/param bytes mismatch", desc_i);
      end
      if (rec_desc_index_o != 16'(desc_i)) begin
        $fatal(1, "record %0d index mismatch: %0d", desc_i, rec_desc_index_o);
      end
    end
  endtask

  task automatic retire_record;
    begin
      idle_cycles(3);
      @(negedge clk_hp_i);
      retired_i = 1'b1;
      @(negedge clk_hp_i);
      retired_i = 1'b0;
    end
  endtask

  task automatic expect_fault;
    int unsigned s_wait;
    begin
      s_wait = 0;
      while (!fault_req_o) begin
        @(posedge clk_hp_i);
        s_wait++;
        if (s_wait > 4000) $fatal(1, "NPU decoder fault never reported in %s", s_phase);
      end
      if ({28'd0, fault_code_o} != s_exp_fcode) begin
        $fatal(1, "NPU decoder fault code mismatch: got %0d expected %0d (%s)", fault_code_o,
               s_exp_fcode, s_phase);
      end
      if (fault_desc_o != s_exp_findex) begin
        $fatal(1, "NPU decoder fault index mismatch: got %0d expected %0d (%s)", fault_desc_o,
               s_exp_findex, s_phase);
      end
      if (s_mode == 32'd2) begin
        if (fault_addr_o != s_rderr_addr) begin
          $fatal(1, "NPU decoder fault address mismatch: got %h expected %h", fault_addr_o,
                 s_rderr_addr);
        end
        if (s_rderr_badid == 32'd0) begin
          if (fault_info_o[1:0] != s_rderr_code[1:0] || fault_info_o[3:2] != 2'd1 ||
              fault_info_o[15:8] != 8'd255) begin
            $fatal(1, "NPU decoder fault info mismatch: %h", fault_info_o);
          end
        end
      end else begin
        if (s_exp_wordless) begin
          if (fault_addr_o != (s_job_base + s_exp_findex * 32'd128)) begin
            $fatal(1, "NPU decoder wordless fault address mismatch: got %h expected %h",
                   fault_addr_o, s_job_base + s_exp_findex * 32'd128);
          end
        end else if (fault_addr_o != (s_job_base + s_exp_findex * 32'd128 + s_exp_fword * 32'd4)) begin
          $fatal(1, "NPU decoder fault address mismatch: got %h expected %h", fault_addr_o,
                 s_job_base + s_exp_findex * 32'd128 + s_exp_fword * 32'd4);
        end
        if (fault_info_o != {16'd0, 8'd255, 4'd0, 2'd0, 2'd0}) begin
          $fatal(1, "NPU decoder validation fault info mismatch: %h", fault_info_o);
        end
      end
      // terminal: no record emission, no new fetch while the fault is held
      idle_cycles(20);
      if (rec_valid_o || s_dec_read_req_valid || !fault_req_o) begin
        $fatal(1, "NPU decoder kept working after a terminal fault");
      end
      // coordinated cancel returns the decoder to idle
      @(negedge clk_hp_i);
      clear_i = 1'b1;
      idle_cycles(2);
      @(negedge clk_hp_i);
      clear_i = 1'b0;
      idle_cycles(10);
      if (busy_o || fault_req_o) $fatal(1, "NPU decoder did not clear after cancel");
    end
  endtask

  initial begin
    s_phase         = "plusargs";
    s_hold_ar_i     = 1'b0;
    s_hold_r_i      = 1'b0;
    s_pause_armed_i = 1'b0;
    // keep the plusarg targets procedural variables for Icarus vpi
    s_job_base      = 32'd0;
    s_job_count     = 32'd0;
    s_mode          = 32'd0;
    s_exp_fcode     = 32'd0;
    s_exp_findex    = 32'd0;
    s_exp_fword     = 32'hffff_ffff;
    s_rderr_addr    = 32'hffff_ffff;
    s_rderr_code    = 32'd0;
    s_rderr_badid   = 32'd0;
    if (!$value$plusargs("IMG=%s", s_img_path)) $fatal(1, "missing +IMG");
    if (!$value$plusargs("BASE=%h", s_job_base)) $fatal(1, "missing +BASE");
    if (!$value$plusargs("COUNT=%d", s_job_count)) $fatal(1, "missing +COUNT");
    if (!$value$plusargs("MODE=%d", s_mode)) $fatal(1, "missing +MODE");
    if (!$value$plusargs("FCODE=%d", s_exp_fcode)) $fatal(1, "missing +FCODE");
    if (!$value$plusargs("FINDEX=%d", s_exp_findex)) $fatal(1, "missing +FINDEX");
    if (!$value$plusargs("FWORD=%d", s_exp_fword)) $fatal(1, "missing +FWORD");
    if (!$value$plusargs("RDERR_ADDR=%h", s_rderr_addr)) $fatal(1, "missing +RDERR_ADDR");
    if (!$value$plusargs("RDERR_CODE=%d", s_rderr_code)) $fatal(1, "missing +RDERR_CODE");
    if (!$value$plusargs("RDERR_BADID=%d", s_rderr_badid)) $fatal(1, "missing +RDERR_BADID");
    s_exp_wordless = (s_exp_fword == 32'hffff_ffff);
    for (int unsigned index = 0; index < MemoryBytes; index++) begin
      s_memory[index] = 8'(index >> 12) ^ 8'(index);
    end

    set_phase("reset");
    repeat (4) @(posedge clk_hp_i);
    @(negedge clk_hp_i);
    rst_hp_n_i = 1'b1;
    idle_cycles(4);

    set_phase("load image");
    load_image(s_img_path, s_job_base);
    if (s_mode == 32'd3) begin
      s_pause_armed_i = 1'b1;
    end

    if ((s_mode == 32'd1) || (s_mode == 32'd2)) begin
      // validation/fetch fault: the fault may follow earlier valid records
      set_phase("fault traversal");
      launch_job();
      for (int unsigned desc = 0; desc < 32'(s_exp_findex); desc++) begin
        while (!rec_valid_o) begin
          @(posedge clk_hp_i);
          if (fault_req_o) $fatal(1, "NPU decoder faulted early at %0d", desc);
        end
        if (rec_desc_index_o != 16'(desc)) $fatal(1, "NPU decoder record order broken");
        check_record(desc);
        @(negedge clk_hp_i);
        rec_ready_i = 1'b1;
        @(negedge clk_hp_i);
        rec_ready_i = 1'b0;
        retire_record();
      end
      expect_fault();
    end else begin
      // accept (mode 0) and pause-during-fetch (mode 3)
      set_phase("accept");
      launch_job();
      for (int unsigned desc = 0; desc < 32'(s_job_count); desc++) begin
        while (!rec_valid_o) begin
          @(posedge clk_hp_i);
          if (fault_req_o) $fatal(1, "NPU decoder faulted on a valid image at %0d", desc);
        end
        if (rec_desc_index_o != 16'(desc)) $fatal(1, "NPU decoder record order broken");
        check_record(desc);
        @(negedge clk_hp_i);
        rec_ready_i = 1'b1;
        @(negedge clk_hp_i);
        rec_ready_i = 1'b0;
        retire_record();
      end
      if (!s_saw_all_done_q) $fatal(1, "NPU decoder all_done missing");
      idle_cycles(10);
      if (busy_o || fault_req_o) $fatal(1, "NPU decoder stayed busy after all_done");
      if (s_ar_count != 32'(s_job_count)) begin
        $fatal(1, "NPU decoder fetch count mismatch: %0d", s_ar_count);
      end
    end

    if ((s_mode == 32'd1) || (s_mode == 32'd2)) begin
      // no reuse of the launch slot after terminal without a fresh start; a
      // fresh job_start re-fetches and re-validates the same image
      set_phase("no reuse");
      idle_cycles(20);
      if (rec_valid_o || s_dec_read_req_valid) begin
        $fatal(1, "NPU decoder reused the terminal launch slot");
      end
      if ((s_mode == 32'd1) || (s_mode == 32'd2)) begin
        launch_job();
        for (int unsigned desc = 0; desc < 32'(s_exp_findex); desc++) begin
          while (!rec_valid_o) begin
            @(posedge clk_hp_i);
            if (fault_req_o) $fatal(1, "NPU decoder refetch faulted early at %0d", desc);
          end
          check_record(desc);
          @(negedge clk_hp_i);
          rec_ready_i = 1'b1;
          @(negedge clk_hp_i);
          rec_ready_i = 1'b0;
          retire_record();
        end
        expect_fault();
      end
    end

    set_phase("done");
    $display("NPU job decoder test passed");
    $finish;
  end

  initial begin
    repeat (500000) @(posedge clk_hp_i);
    $fatal(1, "NPU decoder TB global timeout in %s", s_phase);
  end
endmodule
