`timescale 1ns / 1ps

// NPU-P4 shell-level job admission test: apb4_npu (the npu_reg PCLK shell,
// the npu_control_cdc mailboxes, npu_core, and the production npu_dma)
// exercised entirely through the software APB4 ABI over a byte-memory AXI BFM
// with per-channel hold knobs. The descriptor image, the golden output
// window, and the expected fault address come from plusargs generated by
// tests/test_npu_rtl_p3.py; stored bytes must equal the pinned reference
// output byte-exactly.
//
// Admission coverage: accepted START with READY=1 (no PSLVERR) with
// launch-slot/BUSY visibility, polled DONE completion with the full terminal
// mirror and byte-exact stores, DONE delivery on irq_o with W1C release,
// IRQ_TEST never producing a completion, second START while BUSY rejected
// without side effect, START rejected while a terminal IRQ is pending and
// accepted again after the ack, RESULT_VALID clearing on an accepted START
// but not on IRQ W1C, software ABORT of a store-stalled job with terminal
// ABORTED and a successful recovery rerun, the no-progress watchdog under a
// stalled read channel, and descriptor validation error propagation.
`include "npu_define.svh"

module npu_job_tb;
  localparam logic [31:0] NpuBase = 32'h1001_b000;
  localparam logic [31:0] SramBase = 32'h3000_0000;
  localparam int unsigned MemoryBytes = 524288;
  localparam int unsigned PhaseTimeout = 200000;

  // plusarg case configuration
  string              s_img_path;
  string              s_gold_path;
  logic        [31:0] s_job_base;
  logic        [31:0] s_bad_base;
  logic        [31:0] s_bad_faddr;
  logic        [31:0] s_timeout;
  logic        [31:0] s_wdog;
  logic        [31:0] s_job_id;
  logic        [31:0] s_gold_base;
  logic        [31:0] s_gold_bytes;

  logic               clk_i = 1'b0;
  logic               clk_hp_i = 1'b0;
  logic               rst_n_i = 1'b0;
  logic               rst_hp_n_i = 1'b0;
  logic        [ 1:0] resource_owner_i = 2'd0;
  logic               resource_owner_lock_i = 1'b0;
  logic               resource_quiesce_i = 1'b0;
  logic               resource_reset_i = 1'b0;
  logic               idle_o;
  logic               block_ack_o;
  logic               irq_o;
  logic               hp_block_new_i = 1'b0;
  logic               hp_pause_ack_o;
  logic               hp_flush_i = 1'b0;
  logic               hp_flush_busy_o;
  logic               hp_idle_o;
  logic        [31:0] s_value;

  logic        [ 7:0] s_memory                     [0:MemoryBytes-1];
  logic        [ 7:0] s_golden                     [0:MemoryBytes-1];
  // read channel BFM state
  logic               s_rvalid_q;
  logic        [ 1:0] s_rresp_q;
  logic        [31:0] s_raddr_q;
  logic        [63:0] s_rdata_q;
  logic        [ 2:0] s_rsize_q;
  logic        [ 8:0] s_rbeats_q;
  // write channel BFM state
  logic               s_aw_pending_q;
  logic        [31:0] s_awaddr_q;
  logic        [ 8:0] s_wbeats_q;
  logic               s_bvalid_q;
  // hold knobs and counters
  logic               s_hold_ar_i;
  logic               s_hold_r_i;
  logic               s_hold_aw_i;
  logic               s_hold_w_i;
  logic               s_hold_b_i;
  int unsigned        s_aw_count;
  int unsigned        s_aw_base;
  int unsigned        s_rd_outstanding_q;
  int unsigned        s_wr_outstanding_q;
  string              s_phase;
  int unsigned        s_phase_id;
  int unsigned        s_phase_id_q;
  int unsigned        s_phase_cycles_q;

  apb4_if apb4 (
      .pclk   (clk_i),
      .presetn(rst_n_i)
  );
  axi4_if #(
      .ADDR_WIDTH(32),
      .DATA_WIDTH(64),
      .ID_WIDTH  (3),
      .USER_WIDTH(1)
  ) npu_axi4 (
      clk_hp_i,
      rst_hp_n_i
  );

  always #5 clk_i = ~clk_i;
  always #7 clk_hp_i = ~clk_hp_i;

  apb4_npu u_dut (
      .clk_i                (clk_i),
      .rst_n_i              (rst_n_i),
      .clk_hp_i             (clk_hp_i),
      .rst_hp_n_i           (rst_hp_n_i),
      .resource_owner_i     (resource_owner_i),
      .resource_owner_lock_i(resource_owner_lock_i),
      .resource_quiesce_i   (resource_quiesce_i),
      .resource_reset_i     (resource_reset_i),
      .apb4                 (apb4),
      .idle_o               (idle_o),
      .block_ack_o          (block_ack_o),
      .irq_o                (irq_o),
      .hp_block_new_i       (hp_block_new_i),
      .hp_pause_ack_o       (hp_pause_ack_o),
      .hp_flush_i           (hp_flush_i),
      .hp_flush_busy_o      (hp_flush_busy_o),
      .hp_idle_o            (hp_idle_o),
      .npu_axi4             (npu_axi4)
  );

  function automatic logic [7:0] memory_byte(input logic [31:0] address_i);
    if ((address_i >= SramBase) && (address_i < (SramBase + MemoryBytes))) begin
      return s_memory[address_i-SramBase];
    end
    return 8'd0;
  endfunction

  function automatic logic [63:0] memory_word(input logic [31:0] address_i);
    logic [63:0] data;
    logic [31:0] aligned_address;
    begin
      data            = '0;
      aligned_address = {address_i[31:3], 3'b000};
      for (int unsigned lane = 0; lane < 8; lane++) begin
        data[lane*8+:8] = memory_byte(aligned_address + lane);
      end
      return data;
    end
  endfunction

  // ------------------------------- AXI BFM -------------------------------
  assign npu_axi4.arready = !s_hold_ar_i && !s_rvalid_q;
  assign npu_axi4.rid     = 3'd0;
  assign npu_axi4.rdata   = s_rdata_q;
  assign npu_axi4.rresp   = s_rresp_q;
  assign npu_axi4.rlast   = (s_rbeats_q == 9'd1);
  assign npu_axi4.ruser   = '0;
  assign npu_axi4.rvalid  = !s_hold_r_i && s_rvalid_q;
  assign npu_axi4.awready = !s_hold_aw_i && !s_aw_pending_q && !s_bvalid_q;
  assign npu_axi4.wready  = !s_hold_w_i && s_aw_pending_q && !s_bvalid_q;
  assign npu_axi4.bid     = 3'd0;
  assign npu_axi4.bresp   = 2'b00;
  assign npu_axi4.buser   = '0;
  assign npu_axi4.bvalid  = !s_hold_b_i && s_bvalid_q;

  always_ff @(posedge clk_hp_i or negedge rst_hp_n_i) begin
    if (!rst_hp_n_i) begin
      s_rvalid_q         <= 1'b0;
      s_rresp_q          <= 2'd0;
      s_raddr_q          <= '0;
      s_rdata_q          <= '0;
      s_rsize_q          <= '0;
      s_rbeats_q         <= '0;
      s_aw_pending_q     <= 1'b0;
      s_awaddr_q         <= '0;
      s_wbeats_q         <= '0;
      s_bvalid_q         <= 1'b0;
      s_aw_count         <= 0;
      s_rd_outstanding_q <= 0;
      s_wr_outstanding_q <= 0;
    end else if (hp_flush_i || u_dut.s_dma_clear) begin
      s_rvalid_q         <= 1'b0;
      s_rbeats_q         <= '0;
      s_aw_pending_q     <= 1'b0;
      s_wbeats_q         <= '0;
      s_bvalid_q         <= 1'b0;
      s_rd_outstanding_q <= 0;
      s_wr_outstanding_q <= 0;
    end else begin
      if (npu_axi4.arvalid && npu_axi4.arready) begin
        if (s_rd_outstanding_q != 0) begin
          $fatal(1, "NPU job TB: second outstanding read");
        end
        if ((npu_axi4.araddr & ((32'd1 << npu_axi4.arsize) - 32'd1)) != 32'd0) begin
          $fatal(1, "NPU job TB: unaligned read transfer");
        end
        if ((npu_axi4.arsize != 3'd3) && (npu_axi4.arlen != 8'd0)) begin
          $fatal(1, "NPU job TB: multi-beat narrow read burst");
        end
        if ({1'b0, npu_axi4.araddr[11:0]} + (({5'd0, npu_axi4.arlen} + 13'd1) << npu_axi4.arsize)
            > 13'd4096) begin
          $fatal(1, "NPU job TB: read burst crossed a 4 KiB boundary");
        end
        s_rvalid_q         <= 1'b1;
        s_rresp_q          <= 2'b00;
        s_raddr_q          <= npu_axi4.araddr;
        s_rdata_q          <= memory_word(npu_axi4.araddr);
        s_rsize_q          <= npu_axi4.arsize;
        s_rbeats_q         <= {1'b0, npu_axi4.arlen} + 1'b1;
        s_rd_outstanding_q <= s_rd_outstanding_q + 1;
      end else if (s_rvalid_q && npu_axi4.rvalid && npu_axi4.rready) begin
        if (s_rbeats_q == 9'd1) begin
          s_rvalid_q         <= 1'b0;
          s_rbeats_q         <= '0;
          s_rd_outstanding_q <= s_rd_outstanding_q - 1;
        end else begin
          s_raddr_q  <= s_raddr_q + (32'd1 << s_rsize_q);
          s_rdata_q  <= memory_word(s_raddr_q + (32'd1 << s_rsize_q));
          s_rbeats_q <= s_rbeats_q - 1'b1;
        end
      end

      if (npu_axi4.awvalid && npu_axi4.awready) begin
        if (s_wr_outstanding_q != 0) begin
          $fatal(1, "NPU job TB: second outstanding write");
        end
        if (npu_axi4.awaddr[2:0] != 3'd0) begin
          $fatal(1, "NPU job TB: unaligned AXI64 write address");
        end
        if ({1'b0, npu_axi4.awaddr[11:0]} + (({5'd0, npu_axi4.awlen} + 13'd1) << 3)
            > 13'd4096) begin
          $fatal(1, "NPU job TB: write burst crossed a 4 KiB boundary");
        end
        s_aw_pending_q     <= 1'b1;
        s_awaddr_q         <= npu_axi4.awaddr;
        s_wbeats_q         <= {1'b0, npu_axi4.awlen} + 1'b1;
        s_aw_count         <= s_aw_count + 1;
        s_wr_outstanding_q <= s_wr_outstanding_q + 1;
      end
      if (npu_axi4.wvalid && npu_axi4.wready) begin
        if (!s_aw_pending_q) begin
          $fatal(1, "NPU job TB: W without an accepted AW");
        end
        if (npu_axi4.wlast != (s_wbeats_q == 9'd1)) begin
          $fatal(1, "NPU job TB: incorrect WLAST sequence");
        end
        if (npu_axi4.wstrb == 8'd0) begin
          $fatal(1, "NPU job TB: zero-strobe write");
        end
        for (int unsigned lane = 0; lane < 8; lane++) begin
          if (npu_axi4.wstrb[lane]) begin
            if (((s_awaddr_q + 32'(lane)) < SramBase) ||
                ((s_awaddr_q + 32'(lane)) >= (SramBase + MemoryBytes))) begin
              $fatal(1, "NPU job TB: write escaped the memory BFM");
            end
            s_memory[(s_awaddr_q+32'(lane))-SramBase] <= npu_axi4.wdata[lane*8+:8];
          end
        end
        if (s_wbeats_q == 9'd1) begin
          s_aw_pending_q <= 1'b0;
          s_wbeats_q     <= '0;
          s_bvalid_q     <= 1'b1;
        end else begin
          s_awaddr_q <= s_awaddr_q + 32'd8;
          s_wbeats_q <= s_wbeats_q - 1'b1;
        end
      end else if (s_bvalid_q && npu_axi4.bvalid && npu_axi4.bready) begin
        s_bvalid_q         <= 1'b0;
        s_wr_outstanding_q <= s_wr_outstanding_q - 1;
      end
    end
  end

  // Bounded per-phase guard: every phase must finish within PhaseTimeout PCLK
  // cycles; individual waits additionally carry their own poll bounds.
  always_ff @(posedge clk_i or negedge rst_n_i) begin
    if (!rst_n_i) begin
      s_phase_id_q     <= 0;
      s_phase_cycles_q <= 0;
    end else begin
      if (s_phase_id_q != s_phase_id) begin
        s_phase_id_q     <= s_phase_id;
        s_phase_cycles_q <= 0;
      end else begin
        s_phase_cycles_q <= s_phase_cycles_q + 1;
        if (s_phase_cycles_q >= PhaseTimeout) begin
          $fatal(1, "NPU job TB phase timed out: %s", s_phase);
        end
      end
    end
  end

  // ------------------------------ scenario tasks ------------------------------
  task automatic idle_pclk(input int unsigned cycles_i);
    begin
      repeat (cycles_i) @(posedge clk_i);
    end
  endtask

  task automatic idle_hp(input int unsigned cycles_i);
    begin
      repeat (cycles_i) @(posedge clk_hp_i);
    end
  endtask

  task automatic set_phase(input string name_i);
    begin
      @(negedge clk_i);
      s_phase    = name_i;
      s_phase_id = s_phase_id + 1;
    end
  endtask

  task automatic drive_apb_idle;
    begin
      apb4.paddr   = 32'd0;
      apb4.pprot   = 3'd0;
      apb4.psel    = 1'b0;
      apb4.penable = 1'b0;
      apb4.pwrite  = 1'b0;
      apb4.pwdata  = 32'd0;
      apb4.pstrb   = 4'd0;
    end
  endtask

  task automatic apb_write(input logic [11:0] offset_i, input logic [31:0] data_i,
                           input logic [3:0] strobe_i, input logic expected_err_i);
    int unsigned s_wait_cycles;
    logic        s_response_err;
    begin
      @(negedge clk_i);
      apb4.paddr   = NpuBase + offset_i;
      apb4.pwdata  = data_i;
      apb4.pstrb   = strobe_i;
      apb4.pwrite  = 1'b1;
      apb4.psel    = 1'b1;
      apb4.penable = 1'b0;
      #1;
      if (apb4.pready) $fatal(1, "NPU job TB: PREADY asserted during write setup at %h", offset_i);
      @(negedge clk_i);
      apb4.penable  = 1'b1;
      s_wait_cycles = 0;
      #1;
      while (!apb4.pready) begin
        s_wait_cycles++;
        if (s_wait_cycles > 4) $fatal(1, "NPU job TB: write wait timeout at %h", offset_i);
        @(negedge clk_i);
        #1;
      end
      if (s_wait_cycles != 1) begin
        $fatal(1, "NPU job TB: write wait count mismatch at %h: %0d", offset_i, s_wait_cycles);
      end
      if (apb4.pslverr != expected_err_i) begin
        $fatal(1, "NPU job TB: write response mismatch at %h in %s", offset_i, s_phase);
      end
      s_response_err = apb4.pslverr;
      #2;
      if (!apb4.pready || (apb4.pslverr != s_response_err)) begin
        $fatal(1, "NPU job TB: write response was not retained through completion at %h", offset_i);
      end
      @(negedge clk_i);
      drive_apb_idle();
    end
  endtask

  task automatic apb_read(input logic [11:0] offset_i, output logic [31:0] data_o,
                          input logic expected_err_i);
    int unsigned        s_wait_cycles;
    logic        [31:0] s_response_data;
    logic               s_response_err;
    begin
      @(negedge clk_i);
      apb4.paddr   = NpuBase + offset_i;
      apb4.pstrb   = 4'd0;
      apb4.pwrite  = 1'b0;
      apb4.psel    = 1'b1;
      apb4.penable = 1'b0;
      #1;
      if (apb4.pready) $fatal(1, "NPU job TB: PREADY asserted during read setup at %h", offset_i);
      @(negedge clk_i);
      apb4.penable  = 1'b1;
      s_wait_cycles = 0;
      #1;
      while (!apb4.pready) begin
        s_wait_cycles++;
        if (s_wait_cycles > 4) $fatal(1, "NPU job TB: read wait timeout at %h", offset_i);
        @(negedge clk_i);
        #1;
      end
      if (s_wait_cycles != 1) begin
        $fatal(1, "NPU job TB: read wait count mismatch at %h: %0d", offset_i, s_wait_cycles);
      end
      if (apb4.pslverr != expected_err_i) begin
        $fatal(1, "NPU job TB: read response mismatch at %h during %s", offset_i, s_phase);
      end
      s_response_data = apb4.prdata;
      s_response_err  = apb4.pslverr;
      #2;
      if (!apb4.pready || (apb4.prdata != s_response_data) ||
          (apb4.pslverr != s_response_err)) begin
        $fatal(1, "NPU job TB: read response was not retained through completion at %h", offset_i);
      end
      data_o = s_response_data;
      @(negedge clk_i);
      drive_apb_idle();
    end
  endtask

  task automatic expect_read(input logic [11:0] offset_i, input logic [31:0] expected_i);
    begin
      apb_read(offset_i, s_value, 1'b0);
      if (s_value != expected_i) begin
        $fatal(1, "NPU job TB: read mismatch at %h: got %h expected %h (%s)", offset_i, s_value,
               expected_i, s_phase);
      end
    end
  endtask

  task automatic wait_link_up;
    int unsigned s_polls;
    begin
      s_polls = 0;
      apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
      while (s_value[`APB4_NPU__STATUS_RECOVERING] != 1'b0) begin
        s_polls++;
        if (s_polls > 200) $fatal(1, "NPU job TB: link did not reconcile after reset");
        apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
      end
    end
  endtask

  task automatic wait_status_flag(input int unsigned bit_i, input logic value_i,
                                  input int unsigned bound_i);
    int unsigned s_polls;
    begin
      s_polls = 0;
      apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
      while (s_value[bit_i] != value_i) begin
        s_polls++;
        if (s_polls > bound_i) begin
          $fatal(1, "NPU job TB: STATUS bit %0d never became %0d in %s", bit_i, value_i, s_phase);
        end
        apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
      end
    end
  endtask

  task automatic wait_ready;
    begin
      wait_status_flag(`APB4_NPU__STATUS_READY, 1'b1, 10000);
    end
  endtask

  task automatic wait_result_valid;
    begin
      wait_status_flag(`APB4_NPU__STATUS_RESULT_VALID, 1'b1, 100000);
    end
  endtask

  task automatic program_job(input logic [31:0] base_i, input logic [31:0] count_i,
                             input logic [31:0] id_i, input logic [31:0] timeout_i);
    begin
      apb_write(`APB4_NPU__JOB_BASE, base_i, 4'hf, 1'b0);
      apb_write(`APB4_NPU__JOB_COUNT, count_i, 4'hf, 1'b0);
      apb_write(`APB4_NPU__JOB_ID, id_i, 4'hf, 1'b0);
      apb_write(`APB4_NPU__TIMEOUT_CYCLES, timeout_i, 4'hf, 1'b0);
    end
  endtask

  task automatic start_job(input logic expected_err_i);
    begin
      apb_write(`APB4_NPU__CONTROL, 32'h0000_0001, 4'hf, expected_err_i);
    end
  endtask

  task automatic ack_irq(input logic [2:0] mask_i);
    begin
      apb_write(`APB4_NPU__IRQ_STATE, {29'd0, mask_i}, 4'hf, 1'b0);
      expect_read(`APB4_NPU__IRQ_STATE, 32'd0);
    end
  endtask

  task automatic check_terminal(input logic [31:0] code_i, input logic [31:0] fcode_i,
                                input logic [31:0] fdesc_i, input logic [31:0] faddr_i,
                                input logic [31:0] finfo_i, input logic [31:0] completed_i,
                                input logic [31:0] job_id_i, input logic [31:0] irq_i);
    begin
      expect_read(`APB4_NPU__RESULT_CODE, code_i);
      expect_read(`APB4_NPU__RESULT_JOB_ID, job_id_i);
      expect_read(`APB4_NPU__COMPLETED_DESCRIPTORS, completed_i);
      expect_read(`APB4_NPU__FAULT_DESCRIPTOR, fdesc_i);
      expect_read(`APB4_NPU__FAULT_CODE, fcode_i);
      expect_read(`APB4_NPU__FAULT_ADDRESS, faddr_i);
      expect_read(`APB4_NPU__FAULT_INFO, finfo_i);
      expect_read(`APB4_NPU__IRQ_STATE, irq_i);
      wait_status_flag(`APB4_NPU__STATUS_BUSY, 1'b0, 1000);
    end
  endtask

  task automatic load_image(input string path_i);
    logic [31:0] s_img[0:131071];
    begin
      $readmemh(path_i, s_img);
      for (int unsigned index = 0; index < MemoryBytes / 4; index++) begin
        for (int unsigned lane = 0; lane < 4; lane++) begin
          s_memory[index*4+lane] = s_img[index][lane*8+:8];
        end
      end
    end
  endtask

  task automatic load_golden(input string path_i);
    logic [31:0] s_img[0:131071];
    begin
      $readmemh(path_i, s_img);
      for (int unsigned index = 0; index < 32'(s_gold_bytes); index++) begin
        s_golden[index] = s_img[index/4][(index%4)*8+:8];
      end
    end
  endtask

  task automatic check_golden;
    int unsigned s_mismatches;
    begin
      s_mismatches = 0;
      for (int unsigned index = 0; index < 32'(s_gold_bytes); index++) begin
        if (memory_byte(s_gold_base + index) != s_golden[index]) begin
          if (s_mismatches < 8) begin
            $display("NPU job TB: store mismatch at %h: got %h expected %h", s_gold_base + index,
                     memory_byte(s_gold_base + index), s_golden[index]);
          end
          s_mismatches++;
        end
      end
      if (s_mismatches != 0) begin
        $fatal(1, "NPU job TB: golden window has %0d byte mismatches (%s)", s_mismatches, s_phase);
      end
    end
  endtask

  task automatic wait_store_advance;
    int unsigned s_wait;
    begin
      s_wait = 0;
      while (s_aw_count == s_aw_base) begin
        @(posedge clk_hp_i);
        s_wait++;
        if (s_wait > 200000) $fatal(1, "NPU job TB: job never stored in %s", s_phase);
      end
    end
  endtask

  initial begin
    s_phase      = "plusargs";
    s_phase_id   = 0;
    s_hold_ar_i  = 1'b0;
    s_hold_r_i   = 1'b0;
    s_hold_aw_i  = 1'b0;
    s_hold_w_i   = 1'b0;
    s_hold_b_i   = 1'b0;
    s_job_base   = 32'd0;
    s_bad_base   = 32'd0;
    s_bad_faddr  = 32'd0;
    s_timeout    = 32'd0;
    s_wdog       = 32'd0;
    s_job_id     = 32'd0;
    s_gold_base  = 32'd0;
    s_gold_bytes = 32'd0;
    if (!$value$plusargs("IMG=%s", s_img_path)) $fatal(1, "missing +IMG");
    if (!$value$plusargs("GOLD=%s", s_gold_path)) $fatal(1, "missing +GOLD");
    if (!$value$plusargs("GOLD_BASE=%h", s_gold_base)) $fatal(1, "missing +GOLD_BASE");
    if (!$value$plusargs("GOLD_BYTES=%d", s_gold_bytes)) $fatal(1, "missing +GOLD_BYTES");
    if (!$value$plusargs("BASE=%h", s_job_base)) $fatal(1, "missing +BASE");
    if (!$value$plusargs("BAD_BASE=%h", s_bad_base)) $fatal(1, "missing +BAD_BASE");
    if (!$value$plusargs("BAD_FADDR=%h", s_bad_faddr)) $fatal(1, "missing +BAD_FADDR");
    if (!$value$plusargs("TIMEOUT=%d", s_timeout)) $fatal(1, "missing +TIMEOUT");
    if (!$value$plusargs("WDOG=%d", s_wdog)) $fatal(1, "missing +WDOG");
    if (!$value$plusargs("JOBID=%h", s_job_id)) $fatal(1, "missing +JOBID");

    set_phase("reset");
    drive_apb_idle();
    @(negedge clk_i);
    rst_n_i    = 1'b0;
    rst_hp_n_i = 1'b0;
    repeat (4) @(posedge clk_i);
    @(negedge clk_i);
    rst_hp_n_i = 1'b1;
    @(negedge clk_i);
    rst_n_i = 1'b1;
    wait_link_up();
    if (!idle_o || irq_o) $fatal(1, "NPU job TB: reset lifecycle outputs mismatch");
    // P4 advertises the complete executable implementation and READY is live.
    expect_read(`APB4_NPU__CAPABILITY, `APB4_NPU__CAPABILITY_P4);
    expect_read(`APB4_NPU__STATUS, 32'd1);

    set_phase("load image");
    load_image(s_img_path);
    load_golden(s_gold_path);

    // An injected test event is never a completion: no RESULT_VALID, no
    // result identity, and a pending (test) terminal IRQ still blocks START.
    set_phase("irq test is not completion");
    apb_write(`APB4_NPU__IRQ_ENABLE, 32'h0000_0007, 4'hf, 1'b0);
    if (irq_o) $fatal(1, "NPU job TB: interrupt asserted without events");
    apb_write(`APB4_NPU__IRQ_TEST, 32'h0000_0001, 4'hf, 1'b0);
    expect_read(`APB4_NPU__IRQ_STATE, 32'h0000_0001);
    if (!irq_o) $fatal(1, "NPU job TB: enabled test event did not assert irq_o");
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_RESULT_VALID] != 1'b0) begin
      $fatal(1, "NPU job TB: IRQ_TEST created a completion");
    end
    expect_read(`APB4_NPU__RESULT_CODE, 32'd0);
    expect_read(`APB4_NPU__RESULT_JOB_ID, 32'd0);
    start_job(1'b1);
    if (u_dut.u_npu_reg.s_launch_busy_q !== 1'b0) begin
      $fatal(1, "NPU job TB: START accepted with a pending test event");
    end
    apb_write(`APB4_NPU__IRQ_STATE, 32'h0000_0001, 4'hf, 1'b0);
    expect_read(`APB4_NPU__IRQ_STATE, 32'd0);
    idle_pclk(1);
    if (irq_o) $fatal(1, "NPU job TB: test event survived its W1C ack");
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_RESULT_VALID] != 1'b0) begin
      $fatal(1, "NPU job TB: test event left a completion behind");
    end

    // Polled DONE: accepted START, launch-slot/BUSY visibility, terminal
    // mirror, DONE event collection, byte-exact stores.
    set_phase("polled done");
    wait_ready();
    program_job(s_job_base, 32'd1, s_job_id, s_timeout);
    start_job(1'b0);
    if (u_dut.u_npu_reg.s_launch_busy_q !== 1'b1) begin
      $fatal(1, "NPU job TB: accepted START did not latch the launch slot");
    end
    wait_status_flag(`APB4_NPU__STATUS_BUSY, 1'b1, 100);
    wait_result_valid();
    check_terminal(32'd1, 32'd0, 32'hffff_ffff, 32'd0, 32'd0, 32'd1, s_job_id, 32'h1);
    check_golden();
    // The pending terminal IRQ holds READY low and rejects a further START.
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_READY] != 1'b0) begin
      $fatal(1, "NPU job TB: READY high with a pending terminal IRQ");
    end
    start_job(1'b1);
    if (u_dut.u_npu_reg.s_launch_busy_q !== 1'b0) begin
      $fatal(1, "NPU job TB: START accepted with a pending terminal IRQ");
    end
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_RESULT_VALID] != 1'b1) begin
      $fatal(1, "NPU job TB: rejected START disturbed the retained result");
    end
    // W1C ack releases the event but must not clear RESULT_VALID.
    apb_write(`APB4_NPU__IRQ_STATE, 32'h0000_0001, 4'hf, 1'b0);
    expect_read(`APB4_NPU__IRQ_STATE, 32'd0);
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_RESULT_VALID] != 1'b1) begin
      $fatal(1, "NPU job TB: IRQ W1C cleared RESULT_VALID");
    end

    // After the ack START is accepted again; an accepted START (not the W1C)
    // clears RESULT_VALID, and a second START while BUSY errors out with no
    // side effect on the running job.
    set_phase("restart and busy start");
    wait_ready();
    start_job(1'b0);
    if (u_dut.u_npu_reg.s_launch_busy_q !== 1'b1) begin
      $fatal(1, "NPU job TB: accepted restart did not latch the launch slot");
    end
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_RESULT_VALID] != 1'b0) begin
      $fatal(1, "NPU job TB: accepted START did not clear RESULT_VALID");
    end
    if (s_value[`APB4_NPU__STATUS_BUSY] != 1'b1) begin
      $fatal(1, "NPU job TB: BUSY not visible after the accepted restart");
    end
    start_job(1'b1);
    if (u_dut.u_npu_reg.s_launch_busy_q !== 1'b1) begin
      $fatal(1, "NPU job TB: rejected second START disturbed the running job");
    end
    wait_result_valid();
    check_terminal(32'd1, 32'd0, 32'hffff_ffff, 32'd0, 32'd0, 32'd1, s_job_id, 32'h1);
    check_golden();

    // DONE delivery on irq_o: the event asserts the line, W1C releases it.
    set_phase("done irq delivery");
    ack_irq(3'b001);
    wait_ready();
    idle_pclk(1);
    if (irq_o) $fatal(1, "NPU job TB: interrupt asserted without events");
    program_job(s_job_base, 32'd1, s_job_id + 32'd1, s_timeout);
    start_job(1'b0);
    begin
      int unsigned s_wait;
      s_wait = 0;
      while (!irq_o) begin
        @(posedge clk_i);
        s_wait++;
        if (s_wait > 400000) $fatal(1, "NPU job TB: DONE never asserted irq_o in %s", s_phase);
      end
    end
    expect_read(`APB4_NPU__IRQ_STATE, 32'h0000_0001);
    check_terminal(32'd1, 32'd0, 32'hffff_ffff, 32'd0, 32'd0, 32'd1, s_job_id + 32'd1, 32'h1);
    check_golden();
    apb_write(`APB4_NPU__IRQ_STATE, 32'h0000_0001, 4'hf, 1'b0);
    expect_read(`APB4_NPU__IRQ_STATE, 32'd0);
    idle_pclk(1);
    if (irq_o) $fatal(1, "NPU job TB: W1C ack did not release irq_o");

    // Software ABORT of a store-stalled job: the drain waits for the stalled
    // write response, then the terminal is ABORTED with BUSY/DRAINING clear.
    set_phase("abort");
    wait_ready();
    program_job(s_job_base, 32'd1, s_job_id + 32'd2, s_timeout);
    @(negedge clk_hp_i);
    s_hold_b_i = 1'b1;
    s_aw_base  = s_aw_count;
    start_job(1'b0);
    wait_store_advance();
    apb_write(`APB4_NPU__CONTROL, 32'h0000_0002, 4'hf, 1'b0);
    idle_hp(200);
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_RESULT_VALID] != 1'b0) begin
      $fatal(1, "NPU job TB: terminal appeared with a stalled write response");
    end
    @(negedge clk_hp_i);
    s_hold_b_i = 1'b0;
    wait_result_valid();
    check_terminal(32'd3, 32'd0, 32'hffff_ffff, 32'd0, 32'd0, 32'd0, s_job_id + 32'd2, 32'h4);
    wait_status_flag(`APB4_NPU__STATUS_DRAINING, 1'b0, 1000);
    ack_irq(3'b100);

    set_phase("abort recovery");
    wait_ready();
    program_job(s_job_base, 32'd1, s_job_id + 32'd3, s_timeout);
    start_job(1'b0);
    wait_result_valid();
    check_terminal(32'd1, 32'd0, 32'hffff_ffff, 32'd0, 32'd0, 32'd1, s_job_id + 32'd3, 32'h1);
    check_golden();
    ack_irq(3'b001);

    // No-progress watchdog: with the read channel stalled the job cannot make
    // progress; the terminal is ERROR/NO_PROGRESS once the stall releases.
    set_phase("watchdog");
    wait_ready();
    program_job(s_job_base, 32'd1, s_job_id + 32'd4, s_wdog);
    @(negedge clk_hp_i);
    s_hold_ar_i = 1'b1;
    start_job(1'b0);
    idle_hp(3 * s_wdog + 1000);
    apb_read(`APB4_NPU__STATUS, s_value, 1'b0);
    if (s_value[`APB4_NPU__STATUS_RESULT_VALID] != 1'b0) begin
      $fatal(1, "NPU job TB: terminal appeared while the bus was stalled");
    end
    if (s_value[`APB4_NPU__STATUS_BUSY] != 1'b1) begin
      $fatal(1, "NPU job TB: BUSY dropped with a stalled job");
    end
    @(negedge clk_hp_i);
    s_hold_ar_i = 1'b0;
    wait_result_valid();
    check_terminal(32'd2, 32'd8, 32'd0, 32'd0, 32'h0000_ff00, 32'd0, s_job_id + 32'd4, 32'h2);
    ack_irq(3'b010);

    // Descriptor validation error: a version-mismatched record terminates the
    // job ERROR/DESCRIPTOR with the failing index, address, and ERROR event.
    set_phase("descriptor error");
    wait_ready();
    program_job(s_bad_base, 32'd1, s_job_id + 32'd5, s_timeout);
    start_job(1'b0);
    wait_result_valid();
    check_terminal(32'd2, 32'd1, 32'd0, s_bad_faddr, 32'h0000_ff00, 32'd0, s_job_id + 32'd5, 32'h2);
    ack_irq(3'b010);

    set_phase("done");
    wait_ready();
    idle_pclk(1);
    if (!idle_o || irq_o) $fatal(1, "NPU job TB: final lifecycle outputs mismatch");
    $display("NPU job test passed");
    $finish;
  end

  initial begin
    repeat (3000000) @(posedge clk_i);
    $fatal(1, "NPU job TB global timeout in %s", s_phase);
  end
endmodule
