`timescale 1ns / 1ps

// NPU-P3 job-level test: npu_core (ExecutionReady=1, the production launch /
// result / snapshot mailbox endpoint interface) + the production npu_dma over
// a byte-memory BFM with per-channel hold knobs and address-qualified
// SLVERR/DECERR injection. Descriptor images, job parameters, golden output
// windows and expected terminal records come from plusargs generated by
// tests/test_npu_rtl_p3.py; the stored bytes must equal the documented P3
// transport echo (output byte (oy, ox, c) = gather byte c mod G of position
// (oy, ox)) byte-exactly, with row strides, and the PERF snapshot counters
// must equal the BFM traffic counts.
//
// Scenarios: directed transport jobs (CLAMP/CONV/DW/FC/ADD/POOL/GAP, strided,
// multi-descriptor in order), next-layer B-response ordering, DONE
// aggregation, watchdog expiry under a stalled bus, abort/quiesce/resource
// reset/fabric flush mid-job, snapshot mid-job with the response held across
// terminal delivery (no torn counter bank), write/read bus faults, and
// recovery re-runs after each cancellation.
`include "npu_define.svh"

module npu_core_tb;
  localparam logic [31:0] SramBase = 32'h3000_0000;
  localparam int unsigned MemoryBytes = 524288;
  localparam int unsigned PhaseTimeout = 100000;
  localparam logic [7:0] GapFill = 8'ha5;

  // plusarg case configuration
  string               s_img_path;
  string               s_gold_path;
  logic        [ 31:0] s_job_base;
  logic        [ 31:0] s_job_count;
  logic        [ 31:0] s_job_id;
  logic        [ 31:0] s_timeout;
  logic        [ 31:0] s_scen;
  logic        [ 31:0] s_exp_faddr;
  logic        [ 31:0] s_gold_base;
  logic        [ 31:0] s_gold_bytes;
  logic        [ 31:0] s_rderr_addr;
  logic        [ 31:0] s_rderr_code;
  logic        [ 31:0] s_werr_addr;
  logic        [ 31:0] s_werr_code;
  logic        [ 31:0] s_wchk;
  logic        [ 31:0] s_wchk_base;
  logic        [ 31:0] s_wchk_bytes;
  logic        [ 31:0] s_exp_macs;
  logic        [ 31:0] s_exp_pack;

  logic                clk_hp_i = 1'b0;
  logic                rst_hp_n_i = 1'b0;
  logic                launch_valid_i = 1'b0;
  logic                launch_ready_o;
  logic        [127:0] launch_data_i = '0;
  logic                result_valid_o;
  logic                result_ready_i = 1'b1;
  logic        [169:0] result_data_o;
  logic                snapshot_req_valid_i = 1'b0;
  logic                snapshot_req_ready_o;
  logic                snapshot_resp_valid_o;
  logic                snapshot_resp_ready_i = 1'b0;
  logic        [671:0] snapshot_resp_data_o;
  logic        [  3:0] epoch_req_i = 4'd0;
  logic        [  3:0] epoch_ack_o;
  logic                quiesce_req_i = 1'b0;
  logic                quiesce_ack_o;
  logic                busy_o;
  logic                draining_o;
  logic                block_new_i = 1'b0;
  logic                clock_pause_ack_o;
  logic                flush_i = 1'b0;
  logic                flush_busy_o;
  logic                pause_active_o;
  logic                idle_o;
  logic                abort_i = 1'b0;

  // discrete engine interface
  logic                s_dma_clear;
  logic                s_dma_read_req_valid;
  logic                s_dma_read_req_ready;
  logic        [ 31:0] s_dma_read_addr;
  logic        [ 31:0] s_dma_read_bytes;
  logic                s_dma_read_data_valid;
  logic                s_dma_read_data_ready;
  logic        [ 63:0] s_dma_read_data;
  logic        [  7:0] s_dma_read_keep;
  logic                s_dma_read_last;
  logic                s_dma_write_req_valid;
  logic                s_dma_write_req_ready;
  logic        [ 31:0] s_dma_write_addr;
  logic        [ 31:0] s_dma_write_bytes;
  logic                s_dma_write_data_valid;
  logic                s_dma_write_data_ready;
  logic        [ 63:0] s_dma_write_data;
  logic        [  7:0] s_dma_write_keep;
  logic                s_dma_write_last;
  logic                s_dma_write_done;
  logic                s_dma_busy;
  logic                s_dma_read_busy;
  logic                s_dma_write_busy;
  logic                s_dma_pause_ack;
  logic                s_dma_fault;
  logic        [  3:0] s_dma_fault_code;
  logic        [ 31:0] s_dma_fault_addr;
  logic        [  1:0] s_dma_fault_resp;
  logic        [ 63:0] s_dma_read_bytes_cnt;
  logic        [ 63:0] s_dma_write_bytes_cnt;
  logic        [ 63:0] s_dma_stall_cycles;
  logic                s_dma_read_cmd_err;
  logic                s_dma_write_cmd_err;

  logic        [  7:0] s_memory                     [0:MemoryBytes-1];
  logic        [  7:0] s_golden                     [0:MemoryBytes-1];
  // read channel BFM state
  logic                s_rvalid_q;
  logic        [  2:0] s_rid_q;
  logic        [  1:0] s_rresp_q;
  logic        [ 31:0] s_raddr_q;
  logic        [ 63:0] s_rdata_q;
  logic        [  2:0] s_rsize_q;
  logic        [  8:0] s_rbeats_q;
  // write channel BFM state
  logic                s_aw_pending_q;
  logic        [ 31:0] s_awbase_q;
  logic        [ 31:0] s_awaddr_q;
  logic        [  8:0] s_wbeats_q;
  logic                s_bvalid_q;
  logic        [  1:0] s_bresp_q;
  // hold knobs and counters
  logic                s_hold_ar_i;
  logic                s_hold_r_i;
  logic                s_hold_aw_i;
  logic                s_hold_w_i;
  logic                s_hold_b_i;
  int unsigned         s_ar_count;
  int unsigned         s_aw_count;
  int unsigned         s_b_count;
  logic        [ 63:0] s_bfm_read_bytes_q;
  logic        [ 63:0] s_bfm_write_bytes_q;
  int unsigned         s_rd_outstanding_q;
  int unsigned         s_wr_outstanding_q;
  logic        [ 31:0] s_last_desc_fetch_q;
  logic        [  3:0] s_desc_fetch_mask_q;
  string               s_phase;
  int unsigned         s_phase_cycles_q;
  logic                s_progress;

  axi4_if #(
      .ADDR_WIDTH(32),
      .DATA_WIDTH(64),
      .ID_WIDTH  (3),
      .USER_WIDTH(1)
  ) npu_axi4 (
      .aclk   (clk_hp_i),
      .aresetn(rst_hp_n_i)
  );

  npu_core #(
      .ExecutionReady(1'b1)
  ) u_core (
      .clk_hp_i              (clk_hp_i),
      .rst_hp_n_i            (rst_hp_n_i),
      .launch_valid_i        (launch_valid_i),
      .launch_ready_o        (launch_ready_o),
      .launch_data_i         (launch_data_i),
      .result_valid_o        (result_valid_o),
      .result_ready_i        (result_ready_i),
      .result_data_o         (result_data_o),
      .snapshot_req_valid_i  (snapshot_req_valid_i),
      .snapshot_req_ready_o  (snapshot_req_ready_o),
      .snapshot_resp_valid_o (snapshot_resp_valid_o),
      .snapshot_resp_ready_i (snapshot_resp_ready_i),
      .snapshot_resp_data_o  (snapshot_resp_data_o),
      .epoch_req_i           (epoch_req_i),
      .epoch_ack_o           (epoch_ack_o),
      .quiesce_req_i         (quiesce_req_i),
      .quiesce_ack_o         (quiesce_ack_o),
      .busy_o                (busy_o),
      .draining_o            (draining_o),
      .block_new_i           (block_new_i),
      .clock_pause_ack_o     (clock_pause_ack_o),
      .flush_i               (flush_i),
      .flush_busy_o          (flush_busy_o),
      .pause_active_o        (pause_active_o),
      .idle_o                (idle_o),
      .abort_i               (abort_i),
      .dma_clear_o           (s_dma_clear),
      .dma_read_req_valid_o  (s_dma_read_req_valid),
      .dma_read_req_ready_i  (s_dma_read_req_ready),
      .dma_read_addr_o       (s_dma_read_addr),
      .dma_read_bytes_o      (s_dma_read_bytes),
      .dma_read_data_valid_i (s_dma_read_data_valid),
      .dma_read_data_ready_o (s_dma_read_data_ready),
      .dma_read_data_i       (s_dma_read_data),
      .dma_read_keep_i       (s_dma_read_keep),
      .dma_read_last_i       (s_dma_read_last),
      .dma_write_req_valid_o (s_dma_write_req_valid),
      .dma_write_req_ready_i (s_dma_write_req_ready),
      .dma_write_addr_o      (s_dma_write_addr),
      .dma_write_bytes_o     (s_dma_write_bytes),
      .dma_write_data_valid_o(s_dma_write_data_valid),
      .dma_write_data_ready_i(s_dma_write_data_ready),
      .dma_write_data_o      (s_dma_write_data),
      .dma_write_keep_o      (s_dma_write_keep),
      .dma_write_last_o      (s_dma_write_last),
      .dma_write_done_i      (s_dma_write_done),
      .dma_busy_i            (s_dma_busy),
      .dma_read_busy_i       (s_dma_read_busy),
      .dma_write_busy_i      (s_dma_write_busy),
      .dma_pause_ack_i       (s_dma_pause_ack),
      .dma_fault_i           (s_dma_fault),
      .dma_fault_code_i      (s_dma_fault_code),
      .dma_fault_addr_i      (s_dma_fault_addr),
      .dma_fault_resp_i      (s_dma_fault_resp),
      .dma_read_bytes_i      (s_dma_read_bytes_cnt),
      .dma_write_bytes_i     (s_dma_write_bytes_cnt),
      .dma_stall_cycles_i    (s_dma_stall_cycles),
      .dma_read_cmd_err_i    (s_dma_read_cmd_err),
      .dma_write_cmd_err_i   (s_dma_write_cmd_err)
  );

  npu_dma u_dma (
      .clk_hp_i          (clk_hp_i),
      .rst_hp_n_i        (rst_hp_n_i),
      .clear_i           (flush_i || s_dma_clear),
      .block_new_i       (block_new_i),
      .pause_ack_o       (s_dma_pause_ack),
      .read_req_valid_i  (s_dma_read_req_valid),
      .read_req_ready_o  (s_dma_read_req_ready),
      .read_addr_i       (s_dma_read_addr),
      .read_bytes_i      (s_dma_read_bytes),
      .read_data_valid_o (s_dma_read_data_valid),
      .read_data_ready_i (s_dma_read_data_ready),
      .read_data_o       (s_dma_read_data),
      .read_keep_o       (s_dma_read_keep),
      .read_last_o       (s_dma_read_last),
      .write_req_valid_i (s_dma_write_req_valid),
      .write_req_ready_o (s_dma_write_req_ready),
      .write_addr_i      (s_dma_write_addr),
      .write_bytes_i     (s_dma_write_bytes),
      .write_data_valid_i(s_dma_write_data_valid),
      .write_data_ready_o(s_dma_write_data_ready),
      .write_data_i      (s_dma_write_data),
      .write_keep_i      (s_dma_write_keep),
      .write_last_i      (s_dma_write_last),
      .write_done_o      (s_dma_write_done),
      .busy_o            (s_dma_busy),
      .read_busy_o       (s_dma_read_busy),
      .write_busy_o      (s_dma_write_busy),
      .read_bytes_o      (s_dma_read_bytes_cnt),
      .write_bytes_o     (s_dma_write_bytes_cnt),
      .stall_cycles_o    (s_dma_stall_cycles),
      .fault_o           (s_dma_fault),
      .fault_code_o      (s_dma_fault_code),
      .fault_addr_o      (s_dma_fault_addr),
      .fault_resp_o      (s_dma_fault_resp),
      .read_cmd_err_o    (s_dma_read_cmd_err),
      .write_cmd_err_o   (s_dma_write_cmd_err),
      .axi4              (npu_axi4)
  );

  always #5 clk_hp_i = ~clk_hp_i;

  function automatic logic [7:0] memory_byte(input logic [31:0] address_i);
    if ((address_i >= SramBase) && (address_i < (SramBase + MemoryBytes))) begin
      return s_memory[address_i-SramBase];
    end
    return 8'd0;
  endfunction

  function automatic logic [63:0] memory_word(input logic [31:0] address_i);
    logic [63:0] data;
    logic [31:0] aligned_address;
    begin
      data            = '0;
      aligned_address = {address_i[31:3], 3'b000};
      for (int unsigned lane = 0; lane < 8; lane++) begin
        data[lane*8+:8] = memory_byte(aligned_address + lane);
      end
      return data;
    end
  endfunction

  function automatic logic [1:0] bfm_read_resp(input logic [31:0] beat_addr_i);
    if ((s_rderr_addr != 32'hffff_ffff) && (beat_addr_i == s_rderr_addr)) begin
      return s_rderr_code[1:0];
    end
    return 2'b00;
  endfunction

  function automatic logic [3:0] count_ones8(input logic [7:0] value_i);
    logic [3:0] count;
    begin
      count = 4'd0;
      for (int unsigned lane = 0; lane < 8; lane++) begin
        count = count + {3'd0, value_i[lane]};
      end
      return count;
    end
  endfunction

  // ------------------------------- AXI BFM -------------------------------
  assign npu_axi4.arready = !s_hold_ar_i && !s_rvalid_q;
  assign npu_axi4.rid     = s_rid_q;
  assign npu_axi4.rdata   = s_rdata_q;
  assign npu_axi4.rresp   = s_rresp_q;
  assign npu_axi4.rlast   = (s_rbeats_q == 9'd1);
  assign npu_axi4.ruser   = '0;
  assign npu_axi4.rvalid  = !s_hold_r_i && s_rvalid_q;
  assign npu_axi4.awready = !s_hold_aw_i && !s_aw_pending_q && !s_bvalid_q;
  assign npu_axi4.wready  = !s_hold_w_i && s_aw_pending_q && !s_bvalid_q;
  assign npu_axi4.bid     = 3'd0;
  assign npu_axi4.bresp   = s_bresp_q;
  assign npu_axi4.buser   = '0;
  assign npu_axi4.bvalid  = !s_hold_b_i && s_bvalid_q;

  always_ff @(posedge clk_hp_i or negedge rst_hp_n_i) begin
    if (!rst_hp_n_i) begin
      s_rvalid_q          <= 1'b0;
      s_rid_q             <= '0;
      s_rresp_q           <= 2'd0;
      s_raddr_q           <= '0;
      s_rdata_q           <= '0;
      s_rsize_q           <= '0;
      s_rbeats_q          <= '0;
      s_aw_pending_q      <= 1'b0;
      s_awbase_q          <= '0;
      s_awaddr_q          <= '0;
      s_wbeats_q          <= '0;
      s_bvalid_q          <= 1'b0;
      s_bresp_q           <= 2'd0;
      s_ar_count          <= 0;
      s_aw_count          <= 0;
      s_b_count           <= 0;
      s_bfm_read_bytes_q  <= '0;
      s_bfm_write_bytes_q <= '0;
      s_rd_outstanding_q  <= 0;
      s_wr_outstanding_q  <= 0;
      s_last_desc_fetch_q <= '0;
      s_desc_fetch_mask_q <= '0;
    end else if (flush_i || s_dma_clear) begin
      s_rvalid_q         <= 1'b0;
      s_rbeats_q         <= '0;
      s_aw_pending_q     <= 1'b0;
      s_wbeats_q         <= '0;
      s_bvalid_q         <= 1'b0;
      s_rd_outstanding_q <= 0;
      s_wr_outstanding_q <= 0;
    end else begin
      if (npu_axi4.arvalid && npu_axi4.arready) begin
        if (s_rd_outstanding_q != 0) begin
          $fatal(1, "NPU core TB: second outstanding read");
        end
        if ((npu_axi4.araddr & ((32'd1 << npu_axi4.arsize) - 32'd1)) != 32'd0) begin
          $fatal(1, "NPU core TB: unaligned read transfer");
        end
        if ((npu_axi4.arsize != 3'd3) && (npu_axi4.arlen != 8'd0)) begin
          $fatal(1, "NPU core TB: multi-beat narrow read burst");
        end
        if ({1'b0, npu_axi4.araddr[11:0]} + (({5'd0, npu_axi4.arlen} + 13'd1) << npu_axi4.arsize)
            > 13'd4096) begin
          $fatal(1, "NPU core TB: read burst crossed a 4 KiB boundary");
        end
        if ((npu_axi4.araddr >= s_job_base) &&
            (npu_axi4.araddr < (s_job_base + {16'd0, s_job_count[15:0], 7'd0}))) begin
          s_last_desc_fetch_q                                      <= npu_axi4.araddr;
          s_desc_fetch_mask_q[2'((npu_axi4.araddr-s_job_base)>>7)] <= 1'b1;
        end
        s_rvalid_q         <= 1'b1;
        s_rid_q            <= 3'd0;
        s_rresp_q          <= bfm_read_resp(npu_axi4.araddr);
        s_raddr_q          <= npu_axi4.araddr;
        s_rdata_q          <= memory_word(npu_axi4.araddr);
        s_rsize_q          <= npu_axi4.arsize;
        s_rbeats_q         <= {1'b0, npu_axi4.arlen} + 1'b1;
        s_ar_count         <= s_ar_count + 1;
        s_rd_outstanding_q <= s_rd_outstanding_q + 1;
      end else if (s_rvalid_q && npu_axi4.rvalid && npu_axi4.rready) begin
        s_bfm_read_bytes_q <= s_bfm_read_bytes_q + (64'd1 << s_rsize_q);
        if (s_rbeats_q == 9'd1) begin
          s_rvalid_q         <= 1'b0;
          s_rbeats_q         <= '0;
          s_rd_outstanding_q <= s_rd_outstanding_q - 1;
        end else begin
          s_raddr_q  <= s_raddr_q + (32'd1 << s_rsize_q);
          s_rdata_q  <= memory_word(s_raddr_q + (32'd1 << s_rsize_q));
          s_rresp_q  <= bfm_read_resp(s_raddr_q + (32'd1 << s_rsize_q));
          s_rbeats_q <= s_rbeats_q - 1'b1;
        end
      end

      if (npu_axi4.awvalid && npu_axi4.awready) begin
        if (s_wr_outstanding_q != 0) begin
          $fatal(1, "NPU core TB: second outstanding write");
        end
        if (npu_axi4.awaddr[2:0] != 3'd0) begin
          $fatal(1, "NPU core TB: unaligned AXI64 write address");
        end
        if ({1'b0, npu_axi4.awaddr[11:0]} + (({5'd0, npu_axi4.awlen} + 13'd1) << 3)
            > 13'd4096) begin
          $fatal(1, "NPU core TB: write burst crossed a 4 KiB boundary");
        end
        s_aw_pending_q     <= 1'b1;
        s_awbase_q         <= npu_axi4.awaddr;
        s_awaddr_q         <= npu_axi4.awaddr;
        s_wbeats_q         <= {1'b0, npu_axi4.awlen} + 1'b1;
        s_aw_count         <= s_aw_count + 1;
        s_wr_outstanding_q <= s_wr_outstanding_q + 1;
      end
      if (npu_axi4.wvalid && npu_axi4.wready) begin
        if (!s_aw_pending_q) begin
          $fatal(1, "NPU core TB: W without an accepted AW");
        end
        if (npu_axi4.wlast != (s_wbeats_q == 9'd1)) begin
          $fatal(1, "NPU core TB: incorrect WLAST sequence");
        end
        if (npu_axi4.wstrb == 8'd0) begin
          $fatal(1, "NPU core TB: zero-strobe write");
        end
        for (int unsigned lane = 0; lane < 8; lane++) begin
          if (npu_axi4.wstrb[lane]) begin
            if (((s_awaddr_q + 32'(lane)) < SramBase) ||
                ((s_awaddr_q + 32'(lane)) >= (SramBase + MemoryBytes))) begin
              $fatal(1, "NPU core TB: write escaped the memory BFM");
            end
            s_memory[(s_awaddr_q+32'(lane))-SramBase] <= npu_axi4.wdata[lane*8+:8];
          end
        end
        s_bfm_write_bytes_q <= s_bfm_write_bytes_q + {60'd0, count_ones8(npu_axi4.wstrb)};
        if (s_wbeats_q == 9'd1) begin
          s_aw_pending_q <= 1'b0;
          s_wbeats_q <= '0;
          s_bvalid_q <= 1'b1;
          s_bresp_q      <= ((s_werr_addr != 32'hffff_ffff) && (s_awbase_q == s_werr_addr)) ?
                            s_werr_code[1:0] : 2'b00;
        end else begin
          s_awaddr_q <= s_awaddr_q + 32'd8;
          s_wbeats_q <= s_wbeats_q - 1'b1;
        end
      end else if (s_bvalid_q && npu_axi4.bvalid && npu_axi4.bready) begin
        s_bvalid_q         <= 1'b0;
        s_wr_outstanding_q <= s_wr_outstanding_q - 1;
        s_b_count          <= s_b_count + 1;
      end
    end
  end

  // progress watchdog for the phase guard
  assign s_progress = (npu_axi4.arvalid && npu_axi4.arready) ||
                      (npu_axi4.rvalid && npu_axi4.rready) ||
                      (npu_axi4.awvalid && npu_axi4.awready) ||
                      (npu_axi4.wvalid && npu_axi4.wready) ||
                      (npu_axi4.bvalid && npu_axi4.bready) || result_valid_o;

  always_ff @(posedge clk_hp_i or negedge rst_hp_n_i) begin
    if (!rst_hp_n_i) begin
      s_phase_cycles_q <= 0;
    end else begin
      if (s_progress) begin
        s_phase_cycles_q <= 0;
      end else begin
        s_phase_cycles_q <= s_phase_cycles_q + 1;
        if (s_phase_cycles_q >= PhaseTimeout) begin
          $fatal(1, "NPU core TB phase timed out: %s", s_phase);
        end
      end
    end
  end

  // ------------------------------ scenario tasks ------------------------------
  task automatic idle_cycles(input int unsigned cycles_i);
    begin
      repeat (cycles_i) @(posedge clk_hp_i);
    end
  endtask

  task automatic set_phase(input string name_i);
    begin
      @(negedge clk_hp_i);
      s_phase = name_i;
      idle_cycles(1);
    end
  endtask

  task automatic load_image(input string path_i);
    logic [31:0] s_img[0:131071];
    begin
      $readmemh(path_i, s_img);
      for (int unsigned index = 0; index < MemoryBytes / 4; index++) begin
        for (int unsigned lane = 0; lane < 4; lane++) begin
          s_memory[index*4+lane] = s_img[index][lane*8+:8];
        end
      end
    end
  endtask

  task automatic load_golden(input string path_i);
    logic [31:0] s_img[0:131071];
    begin
      $readmemh(path_i, s_img);
      for (int unsigned index = 0; index < 32'(s_gold_bytes); index++) begin
        s_golden[index] = s_img[index/4][(index%4)*8+:8];
      end
    end
  endtask

  task automatic launch_job(input logic [31:0] job_id_i);
    begin
      @(negedge clk_hp_i);
      launch_data_i  = {16'd0, s_job_count[15:0], s_timeout, job_id_i, s_job_base};
      launch_valid_i = 1'b1;
      @(negedge clk_hp_i);
      launch_valid_i = 1'b0;
    end
  endtask

  task automatic wait_result(output logic [169:0] payload_o);
    int unsigned s_wait;
    begin
      s_wait = 0;
      while (!result_valid_o) begin
        @(posedge clk_hp_i);
        s_wait++;
        if (s_wait > 400000) $fatal(1, "NPU core result never arrived in %s", s_phase);
      end
      payload_o = result_data_o;
      @(posedge clk_hp_i);
      idle_cycles(4);
      if (busy_o || draining_o) $fatal(1, "NPU core stayed busy after terminal");
    end
  endtask

  task automatic check_result(input logic [31:0] code_i, input logic [31:0] fcode_i,
                              input logic [31:0] fdesc_i, input logic [31:0] completed_i,
                              input logic [169:0] payload_i, input logic [31:0] job_id_i,
                              input logic [31:0] faddr_i);
    begin
      if (payload_i[127:96] != faddr_i) begin
        $fatal(1, "NPU core fault address mismatch: got %h expected %h (%s)", payload_i[127:96],
               faddr_i, s_phase);
      end
      if ({29'd0, payload_i[162:160]} != code_i) begin
        $fatal(1, "NPU core result code mismatch: got %0d expected %0d (%s)", payload_i[162:160],
               code_i, s_phase);
      end
      if ({28'd0, payload_i[166:163]} != fcode_i) begin
        $fatal(1, "NPU core fault code mismatch: got %0d expected %0d (%s)", payload_i[166:163],
               fcode_i, s_phase);
      end
      if (payload_i[95:64] != fdesc_i) begin
        $fatal(1, "NPU core fault descriptor mismatch: got %h expected %h (%s)", payload_i[95:64],
               fdesc_i, s_phase);
      end
      if (payload_i[63:32] != completed_i) begin
        $fatal(1, "NPU core completed mismatch: got %0d expected %0d (%s)", payload_i[63:32],
               completed_i, s_phase);
      end
      if (payload_i[31:0] != job_id_i) begin
        $fatal(1, "NPU core job id mismatch: got %h expected %h", payload_i[31:0], job_id_i);
      end
    end
  endtask

  task automatic check_golden;
    int unsigned s_mismatches;
    begin
      s_mismatches = 0;
      for (int unsigned index = 0; index < 32'(s_gold_bytes); index++) begin
        if (memory_byte(s_gold_base + index) != s_golden[index]) begin
          if (s_mismatches < 8) begin
            $display("NPU core store mismatch at %h: got %h expected %h", s_gold_base + index,
                     memory_byte(s_gold_base + index), s_golden[index]);
          end
          s_mismatches++;
        end
      end
      if (s_mismatches != 0) begin
        $fatal(1, "NPU core golden window has %0d byte mismatches (%s)", s_mismatches, s_phase);
      end
    end
  endtask

  task automatic do_snapshot(output logic [671:0] payload_o);
    int unsigned s_wait;
    begin
      @(negedge clk_hp_i);
      snapshot_req_valid_i = 1'b1;
      s_wait               = 0;
      while (!snapshot_req_ready_o) begin
        @(posedge clk_hp_i);
        s_wait++;
        if (s_wait > 1000) $fatal(1, "NPU core snapshot request not accepted");
      end
      @(negedge clk_hp_i);
      snapshot_req_valid_i  = 1'b0;
      snapshot_resp_ready_i = 1'b1;
      s_wait                = 0;
      while (!snapshot_resp_valid_o) begin
        @(posedge clk_hp_i);
        s_wait++;
        if (s_wait > 2000) $fatal(1, "NPU core snapshot response missing");
      end
      payload_o = snapshot_resp_data_o;
      @(posedge clk_hp_i);
      @(negedge clk_hp_i);
      snapshot_resp_ready_i = 1'b0;
    end
  endtask

  function automatic logic [63:0] snap_counter(input logic [671:0] payload_i, input int idx_i);
    return payload_i[32+idx_i*64+:64];
  endfunction

  task automatic check_terminal_snapshot(input logic [31:0] retired_i, input logic [31:0] macs_i,
                                         input logic expect_pack_i);
    logic [671:0] s_snap;
    begin
      do_snapshot(s_snap);
      if (s_snap[31:0] != s_job_id) begin
        $fatal(1, "NPU core terminal snapshot job id mismatch: %h", s_snap[31:0]);
      end
      if (snap_counter(s_snap, 0) == 64'd0) $fatal(1, "NPU core ACTIVE_CYCLES is zero");
      // exact unmasked mathematical MAC count of the job's operators
      if (snap_counter(s_snap, 2) != {32'd0, macs_i}) begin
        $fatal(1, "NPU core USEFUL_MACS %0d != expected %0d", snap_counter(s_snap, 2), macs_i);
      end
      // only the MAC operators (CONV/DW/FC) pack patches; elementwise and pool
      // operators never touch the packer
      if (expect_pack_i && (snap_counter(s_snap, 3) == 64'd0)) begin
        $fatal(1, "NPU core PACK_CYCLES is zero for a gathered job");
      end
      if (!expect_pack_i && (snap_counter(s_snap, 3) != 64'd0)) begin
        $fatal(1, "NPU core PACK_CYCLES nonzero for a non-packed job");
      end
      if (snap_counter(s_snap, 5) != (s_bfm_read_bytes_q - s_bfm_read_base_q)) begin
        $fatal(1, "NPU core DMA_READ_BYTES %0d != BFM %0d", snap_counter(s_snap, 5),
               s_bfm_read_bytes_q - s_bfm_read_base_q);
      end
      if (snap_counter(s_snap, 6) != (s_bfm_write_bytes_q - s_bfm_write_base_q)) begin
        $fatal(1, "NPU core DMA_WRITE_BYTES %0d != BFM %0d", snap_counter(s_snap, 6),
               s_bfm_write_bytes_q - s_bfm_write_base_q);
      end
      if (snap_counter(s_snap, 9) != {32'd0, retired_i}) begin
        $fatal(1, "NPU core RETIRED_DESCRIPTORS %0d != %0d", snap_counter(s_snap, 9), retired_i);
      end
    end
  endtask

  logic [63:0] s_bfm_read_base_q;
  logic [63:0] s_bfm_write_base_q;
  task automatic reset_counters;
    begin
      @(negedge clk_hp_i);
      s_bfm_read_base_q  = s_bfm_read_bytes_q;
      s_bfm_write_base_q = s_bfm_write_bytes_q;
    end
  endtask

  // ------------------------------ scenarios ------------------------------
  task automatic scen_directed;
    logic [169:0] s_result;
    begin
      set_phase("directed job");
      reset_counters();
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
      check_terminal_snapshot(s_job_count, s_exp_macs, s_exp_pack[0]);
      if (s_wchk != 32'd0) begin
        // W transport landed byte-exactly in W half 0 (banks 8/9, low/high)
        for (int unsigned k = 0; k < 32'(s_wchk_bytes); k++) begin
          logic [31:0] s_bank_word;
          unique case ((k >> 2) & 1)
            1'd0:
            s_bank_word = u_core.gen_p3_core.u_scheduler.u_local_sram
                .gen_local_bank[8].s_storage_q[k>>3];
            default:
            s_bank_word = u_core.gen_p3_core.u_scheduler.u_local_sram
                .gen_local_bank[9].s_storage_q[k>>3];
          endcase
          if (s_bank_word[(k&3)*8+:8] != memory_byte(s_wchk_base + k)) begin
            $fatal(1, "NPU core W bank mismatch at chunk byte %0d", k);
          end
        end
      end
      idle_cycles(10);
      // no reuse: the terminal launch slot must not produce a second result
      if (result_valid_o) $fatal(1, "NPU core repeated a terminal result");
    end
  endtask

  task automatic scen_b_order;
    logic        [169:0] s_result;
    logic        [671:0] s_snap;
    int unsigned         s_stall;
    begin
      set_phase("B-response ordering");
      reset_counters();
      launch_job(s_job_id);
      // wait for the first store burst of descriptor 0, then stall all B
      while (s_aw_count == 0) begin
        @(posedge clk_hp_i);
        if (fault_o_seen()) $fatal(1, "unexpected fault in B-order scenario");
      end
      @(negedge clk_hp_i);
      s_hold_b_i = 1'b1;
      // with the write response stalled, descriptor 1 must not be fetched and
      // no retirement/terminal may happen
      idle_cycles(200);
      if (s_desc_fetch_mask_q[1]) begin
        $fatal(1, "NPU core fetched descriptor 1 before the last B response");
      end
      if (result_valid_o) $fatal(1, "NPU core published a result with B stalled");
      do_snapshot(s_snap);
      if (snap_counter(s_snap, 9) != 64'd0) begin
        $fatal(1, "NPU core retired a descriptor before its final B response");
      end
      @(negedge clk_hp_i);
      s_hold_b_i = 1'b0;
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
    end
  endtask

  task automatic scen_watchdog;
    logic [169:0] s_result;
    begin
      set_phase("watchdog expiry");
      // block every read after the launch: no progress is possible
      @(negedge clk_hp_i);
      s_hold_ar_i = 1'b1;
      launch_job(s_job_id);
      // the terminal must not appear while the presented address is stalled
      idle_cycles(3 * s_timeout + 1000);
      if (result_valid_o) begin
        $fatal(1, "NPU core invented a result while the bus was stalled");
      end
      if (!busy_o) $fatal(1, "NPU core dropped BUSY with a stalled job");
      @(negedge clk_hp_i);
      s_hold_ar_i = 1'b0;
      wait_result(s_result);
      check_result(32'd2, 32'd8, 32'd0, 32'd0, s_result, s_job_id, s_exp_faddr);
    end
  endtask

  task automatic scen_abort;
    logic [169:0] s_result;
    begin
      set_phase("abort mid-job");
      // stall write responses so no descriptor can retire before the abort
      @(negedge clk_hp_i);
      s_hold_b_i = 1'b1;
      launch_job(s_job_id);
      while (s_aw_count == 0) begin
        @(posedge clk_hp_i);
      end
      @(negedge clk_hp_i);
      abort_i = 1'b1;
      @(negedge clk_hp_i);
      abort_i = 1'b0;
      // the drain waits for the stalled accepted write; no terminal meanwhile
      idle_cycles(100);
      if (result_valid_o) begin
        $fatal(1, "NPU core published a terminal while a write response was stalled");
      end
      @(negedge clk_hp_i);
      s_hold_b_i = 1'b0;
      wait_result(s_result);
      check_result(32'd3, 32'd0, 32'hffff_ffff, 32'd0, s_result, s_job_id, s_exp_faddr);
      if (result_valid_o) $fatal(1, "NPU core repeated the aborted result");
      // partial stores are defined: every written byte equals the golden
      // content of a completed segment, the rest stays at the prefill value
      for (int unsigned index = 0; index < 32'(s_gold_bytes); index++) begin
        if ((memory_byte(
                s_gold_base + index
            ) != s_golden[index]) && (memory_byte(
                s_gold_base + index
            ) != GapFill)) begin
          $fatal(1, "NPU core abort left a torn byte at %h", s_gold_base + index);
        end
      end
      // recovery: a fresh launch runs to DONE
      set_phase("abort recovery rerun");
      reset_counters();
      load_image(s_img_path);
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
      s_job_id = s_job_id + 32'd1;
    end
  endtask

  task automatic scen_quiesce;
    logic [169:0] s_result;
    begin
      set_phase("quiesce mid-job");
      launch_job(s_job_id);
      while (s_aw_count == 0) begin
        @(posedge clk_hp_i);
      end
      @(negedge clk_hp_i);
      quiesce_req_i = 1'b1;
      // the acknowledge is a genuine round trip with a job in flight
      if (quiesce_ack_o) $fatal(1, "NPU core quiesce acknowledged combinationally");
      wait_result(s_result);
      check_result(32'd3, 32'd0, 32'hffff_ffff, 32'd0, s_result, s_job_id, s_exp_faddr);
      // the terminal result is latched for delivery, then the ack must rise
      idle_cycles(4);
      if (!quiesce_ack_o) $fatal(1, "NPU core quiesce never acknowledged");
      @(negedge clk_hp_i);
      quiesce_req_i = 1'b0;
      idle_cycles(4);
      if (quiesce_ack_o) $fatal(1, "NPU core quiesce acknowledge stuck");
      set_phase("quiesce recovery rerun");
      reset_counters();
      load_image(s_img_path);
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
      s_job_id = s_job_id + 32'd1;
    end
  endtask

  task automatic scen_reset;
    logic [169:0] s_result;
    begin
      set_phase("resource reset mid-job");
      launch_job(s_job_id);
      while (s_aw_count == 0) begin
        @(posedge clk_hp_i);
      end
      @(negedge clk_hp_i);
      epoch_req_i = epoch_req_i + 4'd1;
      // the endpoint must stop/drain, re-acknowledge and publish the retained
      // RESET_CANCELLED diagnostic
      wait_result(s_result);
      if (epoch_ack_o != epoch_req_i) $fatal(1, "NPU core did not re-ack the fresh epoch");
      check_result(32'd4, 32'd10, 32'hffff_ffff, 32'd0, s_result, s_job_id, s_exp_faddr);
      set_phase("reset recovery rerun");
      reset_counters();
      load_image(s_img_path);
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
      s_job_id = s_job_id + 32'd1;
    end
  endtask

  task automatic scen_flush;
    logic [169:0] s_result;
    begin
      set_phase("fabric flush mid-job");
      launch_job(s_job_id);
      while (s_aw_count == 0) begin
        @(posedge clk_hp_i);
      end
      @(negedge clk_hp_i);
      flush_i     = 1'b1;
      epoch_req_i = epoch_req_i + 4'd1;
      idle_cycles(6);
      @(negedge clk_hp_i);
      flush_i = 1'b0;
      // a cancelled job never reports DONE; the recovery token is
      // RESET_CANCELLED after the fresh epoch is acknowledged
      wait_result(s_result);
      check_result(32'd4, 32'd10, 32'hffff_ffff, 32'd0, s_result, s_job_id, s_exp_faddr);
      // idle flush: no artificial job event
      set_phase("idle flush");
      idle_cycles(10);
      @(negedge clk_hp_i);
      flush_i     = 1'b1;
      epoch_req_i = epoch_req_i + 4'd1;
      idle_cycles(6);
      @(negedge clk_hp_i);
      flush_i = 1'b0;
      idle_cycles(20);
      if (result_valid_o) $fatal(1, "NPU core idle flush invented a job event");
      set_phase("flush recovery rerun");
      reset_counters();
      load_image(s_img_path);
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
      s_job_id = s_job_id + 32'd1;
    end
  endtask

  task automatic scen_snapshot_race;
    logic [169:0] s_result;
    logic [671:0] s_snap;
    logic [671:0] s_snap_hold;
    begin
      set_phase("snapshot across terminal");
      reset_counters();
      launch_job(s_job_id);
      // request a capture while the job is active, then hold the response
      // back across the terminal delivery
      @(negedge clk_hp_i);
      snapshot_req_valid_i = 1'b1;
      while (!snapshot_req_ready_o) begin
        @(posedge clk_hp_i);
      end
      @(negedge clk_hp_i);
      snapshot_req_valid_i = 1'b0;
      while (!snapshot_resp_valid_o) begin
        @(posedge clk_hp_i);
      end
      s_snap = snapshot_resp_data_o;
      // hold the response; the job terminates in the meantime
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      idle_cycles(10);
      if (!snapshot_resp_valid_o) $fatal(1, "NPU core withdrew the snapshot response");
      if (snapshot_resp_data_o != s_snap) begin
        $fatal(1, "NPU core snapshot payload changed across terminal delivery");
      end
      // the capture is the pre-terminal active bank: strictly less traffic
      // than the final counts, and the job token matches
      if (s_snap[31:0] != s_job_id) $fatal(1, "NPU core snapshot job id mismatch");
      if (snap_counter(s_snap, 5) >= s_bfm_read_bytes_q) begin
        $fatal(1, "NPU core mid-job capture was not taken before the terminal traffic");
      end
      @(negedge clk_hp_i);
      snapshot_resp_ready_i = 1'b1;
      @(posedge clk_hp_i);
      @(negedge clk_hp_i);
      snapshot_resp_ready_i = 1'b0;
      // the retained terminal bank now reports the final counters
      check_terminal_snapshot(s_job_count, s_exp_macs, s_exp_pack[0]);
      check_golden();
    end
  endtask

  task automatic scen_write_fault;
    logic [169:0] s_result;
    begin
      set_phase("write bus fault");
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd2, 32'd5, 32'd0, 32'd0, s_result, s_job_id, s_exp_faddr);
      // recovery: clear the error injection and rerun to DONE
      set_phase("write fault recovery rerun");
      reset_counters();
      load_image(s_img_path);
      @(negedge clk_hp_i);
      s_werr_addr = 32'hffff_ffff;
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
      s_job_id = s_job_id + 32'd1;
    end
  endtask

  task automatic scen_pause;
    logic        [169:0] s_result;
    logic        [671:0] s_snap;
    int unsigned         s_wait;
    begin
      set_phase("pause mid-job");
      reset_counters();
      launch_job(s_job_id);
      // park the fabric acceptance window while the job is executing
      while (s_ar_count < 2) begin
        @(posedge clk_hp_i);
      end
      @(negedge clk_hp_i);
      block_new_i = 1'b1;
      // the acknowledge may take a few cycles while accepted reads drain
      s_wait      = 0;
      while (!clock_pause_ack_o) begin
        @(posedge clk_hp_i);
        s_wait++;
        if (s_wait > 2000) $fatal(1, "NPU core pause was not acknowledged");
      end
      if (!busy_o) $fatal(1, "NPU core dropped BUSY while paused");
      if (result_valid_o) $fatal(1, "NPU core produced a result while paused");
      // hold the pause far beyond the job timeout: the watchdog must not fire
      idle_cycles(3 * s_timeout);
      if (result_valid_o) begin
        $fatal(1, "NPU core watchdog advanced during the administrative pause");
      end
      do_snapshot(s_snap);
      if (snap_counter(s_snap, 1) == 64'd0) begin
        $fatal(1, "NPU core CLOCK_PAUSE_CYCLES did not count the pause");
      end
      if (snap_counter(s_snap, 0) == 64'd0) $fatal(1, "NPU core ACTIVE_CYCLES stuck at zero");
      @(negedge clk_hp_i);
      block_new_i = 1'b0;
      idle_cycles(4);
      if (clock_pause_ack_o) $fatal(1, "NPU core pause acknowledge stuck");
      wait_result(s_result);
      // identical results after the unblock
      check_result(32'd1, 32'd0, 32'hffff_ffff, s_job_count, s_result, s_job_id, 32'd0);
      check_golden();
    end
  endtask

  task automatic scen_read_fault;
    logic [169:0] s_result;
    begin
      set_phase("read bus fault");
      launch_job(s_job_id);
      wait_result(s_result);
      check_result(32'd2, 32'd4, 32'd0, 32'd0, s_result, s_job_id, s_exp_faddr);
    end
  endtask

  function automatic logic fault_o_seen;
    return s_dma_fault;
  endfunction

  initial begin
    s_phase      = "plusargs";
    s_hold_ar_i  = 1'b0;
    s_hold_r_i   = 1'b0;
    s_hold_aw_i  = 1'b0;
    s_hold_w_i   = 1'b0;
    s_hold_b_i   = 1'b0;
    s_job_base   = 32'd0;
    s_job_count  = 32'd0;
    s_job_id     = 32'd0;
    s_timeout    = 32'd0;
    s_scen       = 32'd0;
    s_exp_faddr  = 32'd0;
    s_gold_base  = 32'd0;
    s_gold_bytes = 32'd0;
    s_rderr_addr = 32'hffff_ffff;
    s_rderr_code = 32'd0;
    s_werr_addr  = 32'hffff_ffff;
    s_werr_code  = 32'd0;
    s_wchk       = 32'd0;
    s_exp_macs   = 32'd0;
    s_exp_pack   = 32'd0;
    s_wchk_base  = 32'd0;
    s_wchk_bytes = 32'd0;
    if (!$value$plusargs("IMG=%s", s_img_path)) $fatal(1, "missing +IMG");
    if (!$value$plusargs("GOLD=%s", s_gold_path)) $fatal(1, "missing +GOLD");
    if (!$value$plusargs("BASE=%h", s_job_base)) $fatal(1, "missing +BASE");
    if (!$value$plusargs("COUNT=%d", s_job_count)) $fatal(1, "missing +COUNT");
    if (!$value$plusargs("JOBID=%h", s_job_id)) $fatal(1, "missing +JOBID");
    if (!$value$plusargs("TIMEOUT=%d", s_timeout)) $fatal(1, "missing +TIMEOUT");
    if (!$value$plusargs("SCEN=%d", s_scen)) $fatal(1, "missing +SCEN");
    if (!$value$plusargs("GOLD_BASE=%h", s_gold_base)) $fatal(1, "missing +GOLD_BASE");
    if (!$value$plusargs("GOLD_BYTES=%d", s_gold_bytes)) $fatal(1, "missing +GOLD_BYTES");
    if (!$value$plusargs("RDERR_ADDR=%h", s_rderr_addr)) $fatal(1, "missing +RDERR_ADDR");
    if (!$value$plusargs("RDERR_CODE=%d", s_rderr_code)) $fatal(1, "missing +RDERR_CODE");
    if (!$value$plusargs("WERR_ADDR=%h", s_werr_addr)) $fatal(1, "missing +WERR_ADDR");
    if (!$value$plusargs("WERR_CODE=%d", s_werr_code)) $fatal(1, "missing +WERR_CODE");
    if (!$value$plusargs("EXP_FADDR=%h", s_exp_faddr)) $fatal(1, "missing +EXP_FADDR");
    if (!$value$plusargs("WCHK=%d", s_wchk)) $fatal(1, "missing +WCHK");
    if (!$value$plusargs("WCHK_BASE=%h", s_wchk_base)) $fatal(1, "missing +WCHK_BASE");
    if (!$value$plusargs("WCHK_BYTES=%d", s_wchk_bytes)) $fatal(1, "missing +WCHK_BYTES");
    if (!$value$plusargs("MACS=%d", s_exp_macs)) $fatal(1, "missing +MACS");
    if (!$value$plusargs("EXP_PACK=%d", s_exp_pack)) $fatal(1, "missing +EXP_PACK");
    for (int unsigned index = 0; index < MemoryBytes; index++) begin
      s_memory[index] = GapFill;
    end

    set_phase("reset");
    repeat (4) @(posedge clk_hp_i);
    @(negedge clk_hp_i);
    rst_hp_n_i = 1'b1;
    idle_cycles(8);
    if (epoch_ack_o != epoch_req_i) $fatal(1, "NPU core epoch not reconciled out of reset");

    set_phase("load image");
    load_image(s_img_path);
    load_golden(s_gold_path);

    unique case (s_scen)
      32'd0:   scen_directed();
      32'd1:   scen_b_order();
      32'd2:   scen_watchdog();
      32'd3:   scen_abort();
      32'd4:   scen_quiesce();
      32'd5:   scen_reset();
      32'd6:   scen_flush();
      32'd7:   scen_snapshot_race();
      32'd8:   scen_write_fault();
      32'd9:   scen_read_fault();
      32'd10:  scen_pause();
      default: $fatal(1, "unknown scenario %0d", s_scen);
    endcase

    set_phase("done");
    $display("NPU core test passed");
    $finish;
  end

  initial begin
    repeat (3000000) @(posedge clk_hp_i);
    $fatal(1, "NPU core TB global timeout in %s", s_phase);
  end

endmodule
