`ifndef RETROSOC_HP_MAILBOX_DEFINE_SVH
`define RETROSOC_HP_MAILBOX_DEFINE_SVH

// verilog_format: off -- preserve software-visible register alignment
`define APB4_HP_MAILBOX__IP_VERSION      12'h000
`define APB4_HP_MAILBOX__CAPABILITY      12'h004
`define APB4_HP_MAILBOX__LP_COMMAND      12'h010
`define APB4_HP_MAILBOX__LP_ARG0         12'h014
`define APB4_HP_MAILBOX__LP_SEQUENCE     12'h018
`define APB4_HP_MAILBOX__LP_DOORBELL     12'h01C
`define APB4_HP_MAILBOX__HP_EVENT        12'h020
`define APB4_HP_MAILBOX__HP_ARG0         12'h024
`define APB4_HP_MAILBOX__HP_SEQUENCE     12'h028
`define APB4_HP_MAILBOX__HP_DOORBELL     12'h02C
`define APB4_HP_MAILBOX__LP_INTR_STATE   12'h030
`define APB4_HP_MAILBOX__LP_INTR_ENABLE  12'h034
`define APB4_HP_MAILBOX__LP_INTR_STATUS  12'h038
`define APB4_HP_MAILBOX__LP_INTR_TEST    12'h03C
`define APB4_HP_MAILBOX__HP_INTR_STATE   12'h040
`define APB4_HP_MAILBOX__HP_INTR_ENABLE  12'h044
`define APB4_HP_MAILBOX__HP_INTR_STATUS  12'h048
`define APB4_HP_MAILBOX__HP_INTR_TEST    12'h04C
// verilog_format: on

`endif

