// Copyright (c) 2026 Yuchi Miao <miaoyuchi@ict.ac.cn>
// retroSoC is licensed under Mulan PSL v2.

`ifndef RETROSOC_SYSCTRL_DEFINE_SVH
`define RETROSOC_SYSCTRL_DEFINE_SVH

`include "mmap_define.svh"

// verilog_format: off -- preserve reviewed column alignment
`define APB4_SYSCTRL__CORESEL                  `SOC_SYSCTRL_CORESEL_OFFSET
`define APB4_SYSCTRL__IPSEL                    `SOC_SYSCTRL_IPSEL_OFFSET
`define APB4_SYSCTRL__PLL_CFG                  `SOC_SYSCTRL_PLL_CFG_OFFSET
`define APB4_SYSCTRL__PLL_CMD                  `SOC_SYSCTRL_PLL_CMD_OFFSET
`define APB4_SYSCTRL__FAULT_STATUS             `SOC_SYSCTRL_FAULT_STATUS_OFFSET
`define APB4_SYSCTRL__FAULT_ADDR               `SOC_SYSCTRL_FAULT_ADDR_OFFSET
`define APB4_SYSCTRL__FAULT_COUNT              `SOC_SYSCTRL_FAULT_COUNT_OFFSET
`define APB4_SYSCTRL__PLL_STATUS               `SOC_SYSCTRL_PLL_STATUS_OFFSET
`define APB4_SYSCTRL__USER_CORE_RESET          `SOC_SYSCTRL_USER_CORE_RESET_OFFSET
`define APB4_SYSCTRL__USER_CORE_STATUS         `SOC_SYSCTRL_USER_CORE_STATUS_OFFSET
`define APB4_SYSCTRL__FAULT_MASTER             `SOC_SYSCTRL_FAULT_MASTER_OFFSET
`define APB4_SYSCTRL__FAULT_DETAIL             `SOC_SYSCTRL_FAULT_DETAIL_OFFSET
`define APB4_SYSCTRL__PERF_CTRL                `SOC_SYSCTRL_PERF_CTRL_OFFSET
`define APB4_SYSCTRL__PERF_MGMT_WAIT_LO        `SOC_SYSCTRL_PERF_MGMT_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_MGMT_WAIT_HI        `SOC_SYSCTRL_PERF_MGMT_WAIT_HI_OFFSET
`define APB4_SYSCTRL__PERF_USER_WAIT_LO        `SOC_SYSCTRL_PERF_USER_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_USER_WAIT_HI        `SOC_SYSCTRL_PERF_USER_WAIT_HI_OFFSET
`define APB4_SYSCTRL__PERF_DMA_WAIT_LO         `SOC_SYSCTRL_PERF_DMA_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_DMA_WAIT_HI         `SOC_SYSCTRL_PERF_DMA_WAIT_HI_OFFSET
`define APB4_SYSCTRL__PERF_APB4_PERIPH_WAIT_LO `SOC_SYSCTRL_PERF_APB4_PERIPH_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_APB4_PERIPH_WAIT_HI `SOC_SYSCTRL_PERF_APB4_PERIPH_WAIT_HI_OFFSET
`define APB4_SYSCTRL__PERF_APB4_SYSTEM_WAIT_LO `SOC_SYSCTRL_PERF_APB4_SYSTEM_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_APB4_SYSTEM_WAIT_HI `SOC_SYSCTRL_PERF_APB4_SYSTEM_WAIT_HI_OFFSET
`define APB4_SYSCTRL__PERF_SDRAM_WAIT_LO       `SOC_SYSCTRL_PERF_SDRAM_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_SDRAM_WAIT_HI       `SOC_SYSCTRL_PERF_SDRAM_WAIT_HI_OFFSET
`define APB4_SYSCTRL__PERF_PSRAM_WAIT_LO       `SOC_SYSCTRL_PERF_PSRAM_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_PSRAM_WAIT_HI       `SOC_SYSCTRL_PERF_PSRAM_WAIT_HI_OFFSET
`define APB4_SYSCTRL__PERF_FLASH_WAIT_LO       `SOC_SYSCTRL_PERF_FLASH_WAIT_LO_OFFSET
`define APB4_SYSCTRL__PERF_FLASH_WAIT_HI       `SOC_SYSCTRL_PERF_FLASH_WAIT_HI_OFFSET
`define APB4_SYSCTRL__TEST_STATUS              `SOC_SYSCTRL_TEST_STATUS_OFFSET
`define APB4_SYSCTRL__RTC_WAKE_STATUS          `SOC_SYSCTRL_RTC_WAKE_STATUS_OFFSET

`define APB4_SYSCTRL__PLL_CMD_APPLY         0
`define APB4_SYSCTRL__PLL_CMD_CLEAR_ERROR   1
`define APB4_SYSCTRL__FAULT_STATUS_PENDING  0
`define APB4_SYSCTRL__PERF_CTRL_ENABLE      0
`define APB4_SYSCTRL__PERF_CTRL_CLEAR       1
`define APB4_SYSCTRL__PERF_CTRL_SNAPSHOT    2
`define APB4_SYSCTRL__TEST_STATUS_PASS      0
`define APB4_SYSCTRL__TEST_STATUS_CODE      8
`define APB4_SYSCTRL__TEST_STATUS_VALID     31
`define APB4_SYSCTRL__RTC_WAKE_STATUS_LIVE  0
`define APB4_SYSCTRL__RTC_WAKE_STATUS_SEEN  1
// verilog_format: on

`endif
