// Copyright (c) 2026 Yuchi Miao <miaoyuchi@ict.ac.cn>
// retroSoC is licensed under Mulan PSL v2.

`ifndef APB4_OPIPSRAM_DEFINE_SVH
`define APB4_OPIPSRAM_DEFINE_SVH

// verilog_format: off -- preserve reviewed register and field alignment
`define APB4_OPIPSRAM__IP_ID                 12'h000
`define APB4_OPIPSRAM__IP_VERSION            12'h004
`define APB4_OPIPSRAM__CAPABILITY            12'h008
`define APB4_OPIPSRAM__CTRL                  12'h00C
`define APB4_OPIPSRAM__COMMAND               12'h010
`define APB4_OPIPSRAM__STATUS                12'h014
`define APB4_OPIPSRAM__PROTOCOL_CFG          12'h018
`define APB4_OPIPSRAM__DEVICE_SIZE           12'h01C
`define APB4_OPIPSRAM__OPI_READ_CMD          12'h020
`define APB4_OPIPSRAM__OPI_WRITE_CMD         12'h024
`define APB4_OPIPSRAM__OPI_REG_READ_CMD      12'h028
`define APB4_OPIPSRAM__OPI_REG_WRITE_CMD     12'h02C
`define APB4_OPIPSRAM__OPI_TIMING            12'h030
`define APB4_OPIPSRAM__HYPER_TIMING          12'h034
`define APB4_OPIPSRAM__CLK_CONFIG            12'h038
`define APB4_OPIPSRAM__CS_TIMING             12'h03C
`define APB4_OPIPSRAM__POWERUP_CYCLES        12'h040
`define APB4_OPIPSRAM__TIMEOUT_CYCLES        12'h044
`define APB4_OPIPSRAM__RX_DELAY              12'h048
`define APB4_OPIPSRAM__PROFILE_STATUS        12'h04C
`define APB4_OPIPSRAM__INDIRECT_CTRL         12'h050
`define APB4_OPIPSRAM__INDIRECT_ADDR         12'h054
`define APB4_OPIPSRAM__INDIRECT_WDATA_LO     12'h058
`define APB4_OPIPSRAM__INDIRECT_WDATA_HI     12'h05C
`define APB4_OPIPSRAM__INDIRECT_RDATA_LO     12'h060
`define APB4_OPIPSRAM__INDIRECT_RDATA_HI     12'h064
`define APB4_OPIPSRAM__LAST_ERROR            12'h068
`define APB4_OPIPSRAM__LAST_ERROR_ADDR       12'h06C
`define APB4_OPIPSRAM__TRAIN_STATUS          12'h070
`define APB4_OPIPSRAM__TRAIN_WINDOW          12'h074
`define APB4_OPIPSRAM__INTR_STATE            12'h080
`define APB4_OPIPSRAM__INTR_ENABLE           12'h084
`define APB4_OPIPSRAM__INTR_STATUS           12'h088
`define APB4_OPIPSRAM__INTR_TEST             12'h08C
`define APB4_OPIPSRAM__PERF_CTRL             12'h090
`define APB4_OPIPSRAM__PERF_READ_BYTES       12'h094
`define APB4_OPIPSRAM__PERF_WRITE_BYTES      12'h098
`define APB4_OPIPSRAM__PERF_COMMANDS         12'h09C
`define APB4_OPIPSRAM__PERF_CACHE_HITS       12'h0A0
`define APB4_OPIPSRAM__PERF_STALL_CYCLES     12'h0A4
`define APB4_OPIPSRAM__PERF_ERROR_COUNT      12'h0A8

`define APB4_OPIPSRAM__CTRL_ENABLE           0
`define APB4_OPIPSRAM__CTRL_MEMORY_ENABLE    1
`define APB4_OPIPSRAM__CTRL_AUTO_INIT        2
`define APB4_OPIPSRAM__CTRL_LINE_BUFFER      3

`define APB4_OPIPSRAM__COMMAND_INIT          0
`define APB4_OPIPSRAM__COMMAND_ABORT         1
`define APB4_OPIPSRAM__COMMAND_SOFT_RESET    2
`define APB4_OPIPSRAM__COMMAND_TRAIN         3

`define APB4_OPIPSRAM__STATUS_BUSY           0
`define APB4_OPIPSRAM__STATUS_INITIALIZED    1
`define APB4_OPIPSRAM__STATUS_READY          2
`define APB4_OPIPSRAM__STATUS_QUIESCED       3
`define APB4_OPIPSRAM__STATUS_TRAINED        4
`define APB4_OPIPSRAM__STATUS_ERROR          5
`define APB4_OPIPSRAM__STATUS_PROFILE_LOCK   6
`define APB4_OPIPSRAM__STATUS_HYPER          7

`define APB4_OPIPSRAM__PROTOCOL_HYPER        0
`define APB4_OPIPSRAM__PROTOCOL_LOCK         1

`define APB4_OPIPSRAM__OPI_CMD_WIDTH16       16
`define APB4_OPIPSRAM__OPI_TIMING_ADDR_LSB   0
`define APB4_OPIPSRAM__OPI_TIMING_ADDR_MSB   1
`define APB4_OPIPSRAM__OPI_TIMING_DUMMY_LSB  2
`define APB4_OPIPSRAM__OPI_TIMING_DUMMY_MSB  9
`define APB4_OPIPSRAM__OPI_TIMING_LATENCY_LSB 10
`define APB4_OPIPSRAM__OPI_TIMING_LATENCY_MSB 14
`define APB4_OPIPSRAM__OPI_TIMING_DQS_READ   15
`define APB4_OPIPSRAM__OPI_TIMING_DQS_WRITE  16

`define APB4_OPIPSRAM__INDIRECT_WRITE        0
`define APB4_OPIPSRAM__INDIRECT_REGISTER     1
`define APB4_OPIPSRAM__INDIRECT_LENGTH_LSB   4
`define APB4_OPIPSRAM__INDIRECT_LENGTH_MSB   7
`define APB4_OPIPSRAM__INDIRECT_START        8

`define APB4_OPIPSRAM__INTR_INIT_DONE        0
`define APB4_OPIPSRAM__INTR_INDIRECT_DONE    1
`define APB4_OPIPSRAM__INTR_TRAIN_DONE       2
`define APB4_OPIPSRAM__INTR_ERROR            3
`define APB4_OPIPSRAM__INTR_TIMEOUT          4

`define APB4_OPIPSRAM__PERF_ENABLE           0
`define APB4_OPIPSRAM__PERF_FREEZE           1
`define APB4_OPIPSRAM__PERF_CLEAR            2

`define APB4_OPIPSRAM__IP_ID_VALUE           32'h4F50_4938
`define APB4_OPIPSRAM__IP_VERSION_VALUE      32'h0001_0000
`define APB4_OPIPSRAM__DEVICE_SIZE_RESET     32'h0080_0000
`define APB4_OPIPSRAM__OPI_READ_CMD_RESET    32'h0001_EE11
`define APB4_OPIPSRAM__OPI_WRITE_CMD_RESET   32'h0001_12ED
`define APB4_OPIPSRAM__OPI_TIMING_RESET      32'h0000_8020
`define APB4_OPIPSRAM__HYPER_TIMING_RESET    32'h0004_0406
`define APB4_OPIPSRAM__CLK_CONFIG_RESET      32'h0000_0000
`define APB4_OPIPSRAM__CS_TIMING_RESET       32'h0404_0201
`define APB4_OPIPSRAM__POWERUP_RESET        32'd64
`define APB4_OPIPSRAM__TIMEOUT_RESET        32'd100000
`define APB4_OPIPSRAM__CAPABILITY_VALUE      32'h0000_007F
// verilog_format: on

`endif
