name: regression-ics55

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: regression-ics55-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verified-open-source-flows:
    uses: ./.github/workflows/_regression.yml
    with:
      suite: pr
      pdk: ICS55
      profile: configs/ci/ics55.mk
      retention_days: 30
